### PR TITLE
Prepare AttributeKeyValue to allow removing AttributeValue

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
>to allow removing AttributeValue

What is the intent? To remove AttributeValue from the codebase?

**Comment by bogdandrutu** [comment]
@tigrannajaryan yes I want to remove the `AttributeValue` from the codebase (or at least generated from Protos) and use `AttributeKeyValue`. I am not sure if `AttributeValue` adds too much and definitely duplicates a lot of code with `AttributeKeyValue`

**Comment by bogdandrutu** [comment]
@tigrannajaryan Alternative is to remove `AttributeKeyValue`, the disadvantage with this is that I want to offer a `initFromSlice(akvs []AttributeKeyValue)` method on the AttributeMap (sort the vector, remove duplicates) which is much faster than `initFromSlice(akvs map[string]AttributeValue)` because constructing the map is more expensive.

**Comment by bogdandrutu** [comment]
@tigrannajaryan the main concern I have is that it is not useful to have both, so was thinking to keep only one of them. If you have a different opinion let me know.

**Comment by tigrannajaryan** [comment]
I agree. I don't think we need both.

**Pull request merged**
