### PR TITLE
Propagate Remote Sampling Host port correctly

### LINKED ISSUE #492: Provide a way to configure Jaeger Agent HTTP Port
Support for Jaeger Remote sampling was added in this PR: https://github.com/open-telemetry/opentelemetry-collector/pull/448 but provides no way to configure the listening port.  As such the http proxy is never started.

This is the struct var that can not be set:
https://github.com/open-telemetry/opentelemetry-collector/blob/b468dee9e0a514db4dab82f6cf7554be539533c9/receiver/jaegerreceiver/trace_receiver.go#L65

I can quickly fix this, but would like to like to merge https://github.com/open-telemetry/opentelemetry-collector/pull/490 first as they are both touching the Jaeger receiver configuration code.

@annanay25  :wave:

### PR DESCRIPTION
**Pull request by joe-elliott**
Added propagation code/tests.

Fixes #492 

cc @annanay25

### CODE REVIEW

**Comment by pjanotti** [comment]
Hi @joe-elliott - is it the idea that this parameter is going to always be required?

**Comment by annanay25** [comment]
Aha, I assumed that remote sampling would be served over the http proxy be default.

**Comment by joe-elliott** [comment]
@pjanotti 
I added a default host port if none is specified that uses Jaeger's default.  This way the operator only has to specify the fetch_endpoint and the it will automatically be hosted at default.  This is now a valid config:

```
receivers:
  jaeger:
    protocols:
      grpc:
    remote_sampling:
      fetch_endpoint: "jaeger-collector:1234"
```

**Comment by joe-elliott** [comment]
Thanks!

**Pull request merged**
