### PR TITLE
Removed groupbytraceprocessor

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

**Description:**
Removed the groupbytrace processor, as a first step in moving it to the contrib repository.

**Link to tracking Issue:** None.

**Testing:** Manual sanity testing.

**Documentation:** None.

### CODE REVIEW

**Comment by jpkrohling** [comment]
There are a couple of points that I would like to clarify before marking this as ready:

- This processor exposes metrics. What's the procedure to add that for a processor in contrib? The only place I could think of was in the `createTraceProcessor`, as I have access to a logger, which I use in case of failure to setup the telemetry.
- Setting up the telemetry requires having access to the telemetry level, which is part of the package `"go.opentelemetry.io/collector/internal/collector/telemetry"`. As it's an internal package, I can't use this package. What should I use instead?
- Same question as above, but for `"go.opentelemetry.io/collector/internal/data/opentelemetry-proto-gen/common/v1"` and `"go.opentelemetry.io/collector/internal/data/opentelemetry-proto-gen/trace/v1"`, used in the tests.

cc @tigrannajaryan, @chris-smith-zocdoc

**Comment by tigrannajaryan** [comment]
Let's wait until the processor is added to contrib and then we can remove from core.

**Comment by jpkrohling** [comment]
> Let's wait until the processor is added to contrib and then we can remove from core.

It should actually be the other way around: first it has to be removed from here, then I can update the collector dependency on -contrib to use the latest master. Otherwise, contrib will not start as two processors with the same name exist. 

I did try it locally here using the collector builder getting the collector from this PR and adding the processor from the -contrib PR (open-telemetry/opentelemetry-collector-contrib#1179) and can confirm that it works, but we do need to coordinate carefully the two merges. Given that we might have a release this week, I'd merge this after the next release.

**Comment by tigrannajaryan** [comment]
> > Let's wait until the processor is added to contrib and then we can remove from core.
> 
> It should actually be the other way around: first it has to be removed from here, then I can update the collector dependency on -contrib to use the latest master. Otherwise, contrib will not start as two processors with the same name exist.
> 
> I did try it locally here using the collector builder getting the collector from this PR and adding the processor from the -contrib PR ([open-telemetry/opentelemetry-collector-contrib#1179](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/1179)) and can confirm that it works, but we do need to coordinate carefully the two merges. Given that we might have a release this week, I'd merge this after the next release.

OK, let's merge after this week's release.

**Comment by tigrannajaryan** [comment]
Please fix the conflict. Core is released, we can merge.

**Comment by jpkrohling** [comment]
Done!

**Comment by jpkrohling** [comment]
@pjanotti, could you please review/merge this one?

**Comment by jpkrohling** [comment]
ping @pjanotti

**Review by pjanotti — APPROVED** [review]
LGTM

**Pull request merged**
