### PR TITLE
otlpjson/trace: skip unknown fields instead of error

### PR DESCRIPTION
**Pull request by bogdandrutu**
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/5312

Signed-off-by: Bogdan <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
Does this change allow the collector to receiver any json payload intending to be an OTEL span without any errors?  So if a user sent `{"key": "value"}`, which matches none of our fields, would the collector skip everything and then return a 200?

**Comment by bogdandrutu** [comment]
Yes, but there is no way otherwise to support adding of new fields correct?

**Comment by TylerHelmuth** [comment]
Ya I guess we have to push that responsibility off to the receivers, otherwise the collector isn't forward/backwards compatible.

**Comment by TylerHelmuth** [comment]
Maybe there could be an option when starting the collector to allow strict enforcement versus skipping unknown values? Some users might want the enforcement.

**Comment by bogdandrutu** [comment]
@TylerHelmuth let's think about that, would you mind opening an issue for that? I do believe that by default we should not fail.

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
> @TylerHelmuth let's think about that, would you mind opening an issue for that? I do believe that by default we should not fail.

Done: https://github.com/open-telemetry/opentelemetry-collector/issues/5935

**Comment by dmitryax** [comment]
Looks like link is the description is wrong

**Comment by bogdandrutu** [comment]
@dmitryax good catch, PTAL

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
