### PR TITLE
Add metric correctness support to testbed

### PR DESCRIPTION
**Pull request by pmcollins**
**Description:** This change adds support for end-to-end metrics correctness tests using generated PICT files.

**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/652

**Documentation:** `metrics/doc.go`

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please rebase after https://github.com/open-telemetry/opentelemetry-collector/pull/1697 is merged :)

**Comment by bogdandrutu** [comment]
Lots of changes in the validator related to rename of the assertion, can this be extracted in a separate PR? Validator is mostly for tracing can it be moved in traces package?

**Comment by pmcollins** [comment]
> Lots of changes in the validator related to rename of the assertion, can this be extracted in a separate PR? Validator is mostly for tracing can it be moved in traces package?

Sure, I'll send out a new PR in a bit.

**Comment by pmcollins** [comment]
Closing due to splitting this into two PRs.

**Pull request closed without merging**
