### PR TITLE
[exporter/otlphttp] Retry only on status code 429/502/503/504

### PR DESCRIPTION
**Pull request by newly12**
## Important (read before submitting)
#6845

**Description:** 
Update retry based on spec change

**Link to tracking Issue:** <Issue number if applicable> 
#6845 

**Testing:** < Describe what testing was performed and which tests were added.>

**Documentation:** < Describe the documentation added.> 

_Please delete paragraphs that you did not use before submitting._

### CODE REVIEW

**Comment by newly12** [comment]
Greetings, could you please take a look at this PR?

**Review by codeboten — APPROVED** [review]

**Comment by kgoralski** [comment]
Hey @newly12, what if the sender will receive just 500 Internal Server Errors? It will not retry on it but I think it should? 
Especially in the case of using daemonsets -> gateway and gateway responding with a high memory limit. It will respond with:

```shell
Exporting failed. The error is not retryable. Dropping data.
Permanent error: error exporting items, request to http://gateway.otel.svc.cluster.local:4318/v1/logs responded with HTTP Status Code 500, Message=data dropped due to high memory usage, Details=[]
```
I think it looks like a retriable error?

**Comment by newly12** [comment]
I think it makes sense to retry on 500 error. I think maybe we can discuss more in https://github.com/open-telemetry/opentelemetry-specification/issues/2915

**Comment by kgoralski** [comment]
> I think it makes sense to retry on 500 error. I think maybe we can discuss more in [open-telemetry/opentelemetry-specification#2915](https://github.com/open-telemetry/opentelemetry-specification/issues/2915)

Found this issue about it:
* https://github.com/open-telemetry/opentelemetry-specification/issues/3314

**Pull request merged**
