### PR TITLE
[chore] Prepare release v1.16.0/v0.110.0

### PR DESCRIPTION
**Pull request by opentelemetrybot**
The following commands were run to prepare this release:
- make chlog-update VERSION=v1.16.0/v0.110.0
- make prepare-release PREVIOUS_VERSION=1[.]15[.]0 RELEASE_CANDIDATE=1.16.0 MODSET=stable
- make prepare-release PREVIOUS_VERSION=0[.]109[.]0 RELEASE_CANDIDATE=0.110.0 MODSET=beta

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

**Comment by jpkrohling** [comment]
Marking as draft, so that https://github.com/open-telemetry/opentelemetry-collector/pull/11204 has a chance to get in this release.

**Comment by codeboten** [comment]
#11204 has merged, the release job will need to be restarted (or this branch rebased via a PR)

**Comment by bogdandrutu** [comment]
This needs a rebase.

**Comment by TylerHelmuth** [comment]
recreated via https://github.com/open-telemetry/opentelemetry-collector/pull/11252

**Pull request closed without merging**
