### PR TITLE
[chore] Prepare release 0.76.0/1.0.0-rc10

### PR DESCRIPTION
**Pull request by opentelemetrybot**
The following commands were run to prepare this release:
- make chlog-update VERSION=v0.76.0/v1.0.0-rc10
- make prepare-release GH=none PREVIOUS_VERSION=1.0.0-rc9 RELEASE_CANDIDATE=1.0.0-rc10 MODSET=stable
- make prepare-release GH=none PREVIOUS_VERSION=0.75.0 RELEASE_CANDIDATE=0.76.0 MODSET=beta

### CODE REVIEW

**Comment by djaglowski** [comment]
```
go.opentelemetry.io/collector@v0.75.1-0.20230424163446-8e33ded10872 requires
	go.opentelemetry.io/collector/exporter@v0.76.0
```

I cannot figure out why any module in either core or contrib would already expect `v0.76.0`. What am I missing here?

**Comment by codeboten** [comment]
Looking at the release from 2 weeks ago, the same error occurred and "skip contrib" was added: https://github.com/open-telemetry/opentelemetry-collector/actions/runs/4594742118/jobs/8114151254

**Comment by djaglowski** [comment]
Thanks @codeboten. I've opened #7566 to document this.

**Comment by djaglowski** [comment]
Closing, will open a new PR to pick up #7568

**Pull request closed without merging**
