### PR TITLE
Rename all github paths from opentelemtry-service to opentelemetry-collector

### PR DESCRIPTION
**Pull request by tigrannajaryan**
This is part of renaming task: https://github.com/open-telemetry/opentelemetry-service/issues/352

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Is this going to build? You change the imports

**Comment by songy23** [comment]
Go module name (`go.mod`) is also updated so build will pass, though I'd suggest holding off this PR until we rename the repo.

**Comment by tigrannajaryan** [comment]
I will rename the repo as soon as I have approvals and will merge the PR.

**Comment by tigrannajaryan** [comment]
OK, I am going to rename the repo and then touch this PR to rebuild it in Travis and make sure everything is OK before merging.

**Comment by bogdandrutu** [comment]
Haha :) you need probably to revert the go.mod changes.

**Comment by tigrannajaryan** [comment]
> Haha :) you need probably to revert the go.mod changes.

The build passed, so I think no need to revert :-)

**Pull request merged**
