### PR TITLE
Expose component configuration schemas

### PR DESCRIPTION
**Pull request by pmcollins**
Issue: https://github.com/open-telemetry/opentelemetry-collector/issues/1995

This change adds a command line utility to generate schema files for each of
the configuration structs used by Collector components. The intent is for these
generated files to be used by documentation utilities and tooling.

The way it works is, given a component, its default configuration struct is
retrieved and introspected, producing field names, types, default values, and
comments. Those are recursively put into a graph of structs, respecting
"squashed" fields and any fields omitted with a "-" tag. Finally, the struct is
marshaled to a yaml file in the directory of the configuration type.

The CLI lets users create a metadata file for either one component or for all
registered components.

Also included is one example schema file.

For reference, preliminary feedback was gathered here: https://github.com/open-telemetry/opentelemetry-collector/pull/2169

### CODE REVIEW

**Review by bogdandrutu — COMMENTED** [review]
I like this, here are couple of suggestions:
1. For the command add it's own go module, similar to what I did for mdatagen to avoid dependencies in the core module that are not needed.
2. Are we planning to generate the go files as well?
3. Are we planning to generate md files as well?

I don't see the generated files, do I miss anything?

**Comment by pmcollins** [comment]
> I like this, here are couple of suggestions:
> 
> 1. For the command add it's own go module, similar to what I did for mdatagen to avoid dependencies in the core module that are not needed.
> 2. Are we planning to generate the go files as well?
> 3. Are we planning to generate md files as well?
> 
> I don't see the generated files, do I miss anything?

Hi @bogdandrutu, thanks!
1. Sounds good, I will create its own go module.
2. I hadn't considered generating go files from the yaml. Do you think that might be preferable, long term?
3. Yeah, I think we'll want to generate md files after this change is done (I'm assuming in a separate command?)

I just included one generated yaml file for this PR: [exporter/otlpexporter/cfg-schema.yaml](https://github.com/open-telemetry/opentelemetry-collector/pull/2210/files#diff-55e9a0f9c5e54a41cd6e050c77cc00073819342cc6d1bd307c167edf299f2b01) Was thinking the rest could be in their own PR. We'll probably also want to add a check in circleci to make sure the yaml isn't out of sync.

**Review by bogdandrutu — COMMENTED** [review]
Is it possible to generate the files without depending on the collector module? If not how can we use this with the contrib repo?

**Comment by pmcollins** [comment]
> Is it possible to generate the files without depending on the collector module? If not how can we use this with the contrib repo?

That's an excellent point @bogdandrutu. I hadn't added support for contrib in the initial PR, but I made a change to do so. The change puts most of the code in a `schemagen` package so that it can be called from contrib. The only thing that's exported is `schemagen.CLI`, which accepts a `components.Factories`. That way core can pass in the core factories, and contrib can pass in the contrib factories. This does mean that contrib would have to have a very small `cmd/schemagen/main.go`. Does this sound good?

**Comment by pmcollins** [comment]
Hi @bogdandrutu and @jrcamp. Any thoughts on this PR?

**Review by jrcamp — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
I think we can iterate and improve, but this is a good starting point.

**Pull request merged**
