### PR TITLE
[receiver/nopreceiver] Add the nopreceiver

### PR DESCRIPTION
**Pull request by evan-bradley**
**Description:**

Add the nopreceiver. This can be helpful if a user wants to start the Collector with a dummy pipeline to only enable extensions. It could also be used to start a dynamically-configured Collector that starts with no config and waits to receive its config from a confmap.Provider that supports reloads.

**Link to tracking Issue:**

Works toward https://github.com/open-telemetry/opentelemetry-collector/issues/7316

**Testing:**

Added lifecycle tests; the receiver doesn't do anything.

**Documentation:**

Added a readme for the component.

### CODE REVIEW

**Comment by evan-bradley** [comment]
cc @djaglowski @tigrannajaryan

**Review by djaglowski — COMMENTED** [review]
LGTM, minor CI issues aside

**Comment by evan-bradley** [comment]
Codecov was complaining that I wasn't testing the generated `Meter` or `Tracer` functions. I already had to manually edit the file to satisfy `make goimpi`, so I just removed them. If we want to take another approach to this I'm open to suggestions. I could test these or even try to use them in the code if we wanted.

**Comment by evan-bradley** [comment]
It looks like I need to leave in the `Meter` and `Tracer` functions. Is the codecov check required to pass to merge this? None of the other components appear to test these and I'd prefer not to write tests just to increase code coverage.

**Review by astencel-sumo — APPROVED** [review]
Love it! :heart:

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
@evan-bradley ptal at the check failure

**Review by djaglowski — APPROVED** [review]

**Comment by evan-bradley** [comment]
@codeboten should be good now, thanks. The codecov check is still failing due to a lack of test coverage on generated code, but it looks like that's an optional check.

**Review by dmitryax — APPROVED** [review]
LGTM. Please update the dependancies

**Comment by evan-bradley** [comment]
@dmitryax Thanks for taking a look. Should be good to go now.

**Comment by evan-bradley** [comment]
@dmitryax CI is green now, minus the code coverage failure due to the lack of tests for generated code.

**Pull request merged**
