### PR TITLE
Add convenience interface in consumertest that implements all consumers

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by jrcamp — APPROVED** [review]
I think it's an improvement.

**Comment by Aneurysm9** [comment]
I wonder whether it's worthwhile to combine the `nopConsumer` and `errConsumer` since the former seems to be identical to the latter with `err == nil`.

**Comment by bogdandrutu** [comment]
@Aneurysm9 is your suggestion to unify only the internal type of also the public API? If it is just the internal we can do it in a followup PR.

**Comment by bogdandrutu** [comment]
@Aneurysm9 please file an issue with this, I will move forward with the current approach since it is an improvement overall.

**Pull request merged**
