### PR TITLE
zipkin translation: move attributes to internal package

### PR DESCRIPTION
**Pull request by jrcamp**
Followup from https://github.com/open-telemetry/opentelemetry-collector/pull/3409#discussion_r649015464

The rest of the files that are currently in `trace/zipkin` are in the process of being moved to a `zipkinv1` directory. After that and this change there will be no `trace/zipkin` directory.

### CODE REVIEW

**Review by carlosalberto — APPROVED** [review]

**Review by rakyll — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by jrcamp** [comment]
@bogdandrutu done

**Comment by bogdandrutu** [comment]
This is an empty PR now, please reopen if I missed something

**Comment by jrcamp** [comment]
> This is an empty PR now, please reopen if I missed something

Looks like you redid it in #3431

**Pull request closed without merging**
