### PR TITLE
Added memory utilization metric & updated tests

### PR DESCRIPTION
**Pull request by james-bebbington**
**Link to tracking Issue:** https://github.com/open-telemetry/opentelemetry-collector/issues/847

**Description:** Added memory utilization metric & updated tests

### CODE REVIEW

**Comment by jrcamp** [comment]
For us at least these aren't useful. What we need is a single `host.memory.utilization` that is a percentage of memory used on a system with no breakdown labels. 

If others have this use case of finer grained utilizations maybe just having a single `host.memory.total` metric. This reduces the number of time series required.

**Comment by bogdandrutu** [comment]
+1 for the total, that should always be available I think :)

**Comment by james-bebbington** [comment]
Can't `host.memory.total` be very easily derived from the usage metric if people want it?

i.e.
```
memory_usage{state=user} = 500
memory_usage{state=free} = 200
==>
memory_total = 700
```

To generate this using the transform processor:

```yaml
metrics_transform:
  transforms:
    - metric_name: system.cpu.time
      action: insert
      new_name: system.cpu.total
      operations:
        - action: aggregate_labels
          label_set: [] # ignore all labels
          aggregation_type: sum
```

Or if you want to generate utilization with no breakdown labels:

```yaml
metrics_transform:
  transforms:
    - metric_name: system.cpu.utilization
      action: update
      operations:
        - action: delete_label_values
          label: state
          values: [ idle ]
        - action: aggregate_labels
          label_set: [ cpu ] # or leave empty if you aren't reporting per cpu (i.e. aggregate away state label)
          aggregation_type: sum
```

**Comment by bogdandrutu** [comment]
> Can't `host.memory.total` be very easily derived from the usage metric if people want it?
> 
> i.e. (pseudo PromQL)
> 
> ```
> memory_usage{state=user} = 500
> memory_usage{state=free} = 200
> ==>
> memory_total = 700
> ```
> 
> To generate this using the transform processor:
> 
> ```yaml
> metricstransform:
>   transforms:
>     - metric_name: system.cpu.time
>       action: insert
>       new_name: system.cpu.total
>       operations:
>         - action: aggregate_labels
>           label_set: [ cpu ] # or leave empty if you aren't reporting per cpu (i.e. aggregate away state label)
>           aggregation_type: sum
> ```
> 

The total will not be 100% constant in this case, I think for CPU the sum of all will be ~total (+/- error). But if we emit it from "NumCPUs" or other source in gopsutil this will be a constant. Does it make sense? Not sure if that matters too much if the total is used for calculating utilization, but if the metric is sum across ~10K hosts it may vary quiet a bit and may be annoying.

> Or if you want to generate utilization with no breakdown labels:
> 
> ```yaml
> metricstransform:
>   transforms:
>     - metric_name: system.cpu.utilization
>       action: update
>       operations:
>         - action: delete_label_values
>           label: state
>           values: [ idle ]
>         - action: aggregate_labels
>           label_set: [ cpu ] # or leave empty if you aren't reporting per cpu (i.e. aggregate away state label)
>           aggregation_type: sum
> ```
> 
> If you're really against that for some reason, I guess I could consider making the reporting of state per utilization an option in the scraper configs?

Not really against this, will need to talk to @jrcamp.

**Comment by james-bebbington** [comment]
> The total will not be 100% constant in this case, I think for CPU the sum of all will be ~total (+/- error). But if we emit it from "NumCPUs" or other source in gopsutil this will be a constant. Does it make sense? Not sure if that matters too much if the total is used for calculating utilization, but if the metric is sum across ~10K hosts it may vary quiet a bit and may be annoying.

I'm not totally sure I get the concern here. I think in all cases the numbers we use should sum to the total exactly:
- For cpu, `gopsutil` [calculates total from the sum of individual values](https://github.com/shirou/gopsutil/blob/master/cpu/cpu.go#L88) anyway
- For filesystem:
  - On Windows `gopsutil` [calculates used from total - free](https://github.com/shirou/gopsutil/blob/master/disk/disk_windows.go#L66)
  - On Unix, we calculate `reserved` as `total - free - used`
- For memory:
  - On Windows `gopsutil` [calculates free from total - used](https://github.com/shirou/gopsutil/blob/master/mem/mem_windows.go#L82)
  - On Linux, `gopsutil` [calculates used from total - free - buffered - cached](https://github.com/shirou/gopsutil/blob/master/mem/mem_linux.go#L170) (there is actually an issue here that this does not include `slab`. I don't know why that't the case; it may be a bug - I will create an issue in gopsutil to follow-up)

Having said that, the sum of utilizations won't be 100% because of tiny fractional rounding errors, but I think that's unavoidable and not really a problem.

**Comment by james-bebbington** [comment]
Since there are different versions of the utilization metric (i.e. different derivations of the raw metrics) that are desired, we have decided to work towards the following instead:

- Support calculation of utilization type metrics in the metric transform processor.
- Create configuration options (in a new processor a new/existing receiver) to specify standard derived metrics such as `system.cpu.utilization`. The metric transform processor will be used to calculate these values under the hood, but this prevents users from having to enter long configuration options such as the one described above.

**Pull request closed without merging**
