### PR TITLE
Add receiver for observIQ stanza

### PR DESCRIPTION
**Pull request by djaglowski**
**Description:**
Add receiver for observIQ's [stanza](https://github.com/observIQ/stanza) log package.

**Testing:** 
- Unit test coverage for 100% of new code.
- Tight benchmarks on direct conversion from stanza's log format to `pdata.Logs`.
- Higher level benchmarks that span reading from a file to emitting from the receiver.

**Documentation:**
- `README` explains `stanza` at a high level and provides many links to `stanza` documentation.
- `testdata` contains some basic configuration examples.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Hi, thank you for your contribution, I would like to propose to move this into the contrib repository to avoid extra dependencies and extra code in core.

**Comment by djaglowski** [comment]
Hi @bogdandrutu. I understand the concern about the additional dependencies and I think this can be improved upon substantially. In regards to your proposal, can I provide a little more context on this PR?

At the collector SIG two weeks ago, there seemed to be consensus that this receiver should at least be seriously considered as a possible default component. As such, I opened the PR against the core repo in the hopes of identifying and addressing any specific issues that would preclude that outcome.

Of course, I'm happy to move this to contrib if that is the best way to move forward, but I was hoping you might provide feedback in light of the above. I've added an agenda item to today's SIG to touch on this with the group.

As an initial improvement on the issue of dependency size, I've updated the PR to user a more selective set of `stanza` packages. The proposed component now adds only about 7% to the compiled binary size. I think we could improve on this further if necessary.

**Comment by tigrannajaryan** [comment]
Hi @djaglowski

I have been looking into this and discussed with @bogdandrutu as well.

We believe that this is a very valuable addition to the Collector. Since it brings a lot of new functionality we would need a bit more time to gain confidence in it than we normally do for smaller components.

At the same time we are currently approaching a GA release for the Collector for traces and metrics and need to make sure any new functionality we bring does not interfere with the GA goals.

To be able to both meet our GA goals while also moving forward with adopting log receiving capabilities I believe we can do the following steps:

1. Add the new the stanza receiver to contrib instead of core. Do not add it to default components yet. Only enable unit tests.
2. Add a concept of experimental build in contrib repo.
3. Mark stanza as an experimental receiver and add it to default components.
4. Add comprehensive functional coverage of all capabilities of stanza receiver using unit test, E2E and perf tests to gain confidence. The coverage should not be simply about code coverage but about covering the actual functionality that is coming from the dependency, including file tailing, parsing, etc.
5. Once we have sufficient coverage and confidence move the stanza from experimental to regular build.
6. Move stanza receiver from contrib to core if necessary.

The experimental build will be part of our regular CircleCI build and will be uploaded as an official Otel Docker image and I envision at least us at Splunk using it for internal tests and experiments so it will definitely not be just a dormant code. I would expect and recommend anyone who is interested in OpenTelemetry Logs to use the experimental build and try the new component.

Sometime during the execution of this plan we will make the 1.0 GA release from regular build without worrying that experimental features may cause problems.

What do you think?

**Comment by djaglowski** [comment]
@tigrannajaryan, thank you for taking the time to look this over more closely and for proposing a detailed path forward. I understand the need to prioritize GA goals and agree that more functional testing is prudent.

Regarding your proposal, I think this approach generally makes sense. 

I’d also like to propose a _parallel_ path. As a premise to this proposal, please consider that stanza’s distinct operators are very much analogous to OT’s distinct components. Therefore, I believe we should consider an integration process that is similarly granular. 

Specifically, I propose that a stanza receiver _which includes a very focused subset of operators_ could be sufficiently vetted sooner rather than later, and included by default in the contrib build. For example, this receiver could initially be limited to include only `file_input`, `json_parser`, and `regex_parser`.

The broader set of operators could be made available in the experimental build, according to the plan you have laid out.

Naturally then, we can look at promoting each operator from experimental to default as sufficient confidence in each is established.

Is this a reasonable way forward?

--- 

One lesser point / question - The testbed does not appear to include much in the way of logs testing, even for Fluent Bit. Is there another component which you believe exemplifies the level of functional testing that you’d like to see?

**Comment by tigrannajaryan** [comment]
>Specifically, I propose that a stanza receiver which includes a very focused subset of operators could be sufficiently vetted sooner rather than later, and included by default in the contrib build. For example, this receiver could initially be limited to include only file_input, json_parser, and regex_parser.

Yes, this is a good point. If it is possible to enable a subset of functionality that stanza agent offers and only expose that subset via stanza receiver that will make it easier for us to enable that vetted subset much faster in the regular build and keep the remaining functionality in the experiment build only.

>Is this a reasonable way forward?

Yes, makes sense.

I suggest that we first start by placing the entire stanza receiver in experimental build, but immediately after we have sufficient coverage and confidence about a certain meaningful subset of features we can move that subset to the regular build.

My personal highest priority would be to support text log file reading, tailing, splitting into records and correct handling of log rotation patterns. If we can get this functionality in the Collector it will be a huge value.

>One lesser point / question - The testbed does not appear to include much in the way of logs testing, even for Fluent Bit. Is there another component which you believe exemplifies the level of functional testing that you’d like to see?

Correct. I imagine us improving the testbed in general to cover logging-related functionality better. Both stanza and Fluentbit tests would benefit from it. For example if we need to test for scenarios where we tail file logs in with log rotation enabled, then we can have a test generator that writes such file logs and rotates them. Such generator can be used by both stanza and Fluentbit tests.

As for a more comprehensive example of tests see the trace tests which have both performance tests for a few interesting scenarios and correctness tests (the pairwise combinatorial input tests).

Generally the end-to-end tests are still work in progress. I am not yet happy with what we have for traces either so we need to aim for more.

**Comment by djaglowski** [comment]
Great, thanks again @tigrannajaryan. It sounds like we have a plan.

I will open a new contrib PR next week.

**Comment by tigrannajaryan** [comment]
@djaglowski excellent, thank you. The demo this Wednesday is still on?

**Comment by djaglowski** [comment]
@tigrannajaryan Yes, and I am planning to drop a note in the collector and logs gitters 24 hours ahead of the meeting.

**Pull request closed without merging**
