### PR TITLE
[extension] Split extension/experimental/storage into a separate module

### LINKED ISSUE #11022: Move `extension/experimental/storage` to a separate module

### PR DESCRIPTION
**Pull request by mx-psi**
#### Description

Fixes #11022

### CODE REVIEW

**Comment by mx-psi** [comment]
@codeboten Should we rename to `extension/storage`? I remember with the `internal/featuregates` separation into a module using the same name was a concern, so I wonder if this is also something we should address here

**Review by TylerHelmuth — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
> @codeboten Should we rename to extension/storage? I remember with the internal/featuregates separation into a module using the same name was a concern, so I wonder if this is also something we should address here

@mx-psi i seem to recall this was only a problem if a package the collector contrib repo depends on also depends on the internal package being created. If not it's not an issue i *think*, we can always prove this by merging the change as is, and updating contrib to see if it fails w/ the errors we were seeing w/ featuregates

**Comment by mx-psi** [comment]
Alright, I am going to try merging this then and if the `make update-otel` goes well

**Comment by mx-psi** [comment]
Need #11029 next

**Pull request merged**
