### PR TITLE
Reimplement prometheus exporter

### PR DESCRIPTION
**Pull request by nabam**
**Description:** 
Implementation of prometheus exporter on top of github.com/prometheus/client_golang/prometheus eliminating opencensus translation layer. 

Changes in behaviour:
- Exported metrics are exposed until `metric_expiration` timeout exceeded

Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/433

### CODE REVIEW

**Comment by nabam** [comment]
Please let me know if that's a valid proposal before I extend the test coverage

**Comment by tigrannajaryan** [comment]
@jmacd or @bogdandrutu will you be able to review this proposal?

**Review by bogdandrutu — COMMENTED** [review]
This is a very complex PR, and I am worried that I will not be able to carefully review, I would propose we start with a simple approach:
* Remove aggregation of non-cumulative histograms or sums for the moment, and support only cumulative values.
* Rebase the PR since there were some changes in `pdata` package.

We can later add aggregation support for non-cumulative data.

**Comment by nabam** [comment]
@bogdandrutu here we go

**Comment by nabam** [comment]
@bogdandrutu happy New Year! Should I expect your review any time soon?

**Pull request closed without merging**
