### PR TITLE
Add Prometheus Remote Write Exporter supporting Cortex - conversion and export for Summary OTLP metrics

### PR DESCRIPTION
**Pull request by huyan0**
This PR is part of a series of PRs implementing a Prometheus remote write exporter supporting Cortex. 
**See  related PR #1577, PR #1643 **  

**Description:** This PR adds export support for summary metrics for Prometheus remote write [integrated backends](https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage), such as Cortex. The exporter drops non-cumulative monotonic, histogram, and summary OTLP metrics.

Please note this metrics exporter does not support Prometheus default labels such as `job` or `instance` labels. An issue addressing Prometheus default labels will be filed later. Another related feature is to derive labels from a Resource. This functionality already exists in the Go SDK and will be implemented in another PR. This feature could allow users to specify which attributes they want to add as labels.

**Link to tracking Issue:**  #1150
Related issues are: 
Metrics aggregation proposal: #1422
Prometheus exporter not functional: #1255
Related spec discussion: [#731](https://github.com/open-telemetry/opentelemetry-specification/issues/731)

**Documentation:** 

* readme.md with sample configuration, file structure, and assumptions

* Design documentation: PR #1464

cc: @huyan0 @alolita @jmacd @bogdandrutu

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Unfortunately this will have to wait couple of weeks until summary support is added back to the metrics internal pipeline

**Comment by bogdandrutu** [comment]
I am sorry that you cannot finish this in time for your internship but we had to make this decision in order to make progress on the protocol

**Comment by huyan0** [comment]
> I am sorry that you cannot finish this in time for your internship but we had to make this decision in order to make progress on the protocol

Not a problem and understood. Really appreciate all the reviews and help from you!

**Comment by bogdandrutu** [comment]
Closing this for the moment, when Summary will be supported will reopen or reuse the code

**Pull request closed without merging**
