### PR TITLE
Change With*Unmarshallers signatures

### LINKED ISSUE #2967: Kafka exporter/receiver change With*Unmarshallers signature
Suggestions are:

- [ ] Remove [Add] from the name.
- [ ] Change to use variadic args instead of a map, the interface has the name already.

### PR DESCRIPTION
**Pull request by sincejune**
**Description:**

- Change method signatures as recommended in #2967 (Closes #2967)

### CODE REVIEW

**Comment by sincejune** [comment]
The CI failure seems unrelated to my change. Could any try to re-run the CI?

**Review by mx-psi — COMMENTED** [review]
We use 'Unmarshaler' (single 'l') on other places in the Collector while we use 'Unmarshallers' here. Both forms are valid English spelling but I think we should consider using a consistent spelling. Maybe this is a good PR to do so (if we want to use the single 'l' version at least)?

**Comment by sincejune** [comment]
This sounds good. I rollbacked my changes to the variables. I'd like to have another PR to rename `Marshaller` to `Marshaler` if you decide to do so.

(Also, please feel free to rollback my last commit if you choose the double `ll` version)

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@sincejune @mx-psi good catch, I would prefer the one "l" version (less spelling).

**Pull request merged**
