### PR TITLE
[chore] Update additional modules to psuedo versions

### PR DESCRIPTION
**Pull request by evan-bradley**
#### Description

Convert additional modules to use pseudo-version numbers. In cases where the module already has a released version, upgrade to pseudo versions to prevent ambiguous import errors (e.g. processor and processortest).

### CODE REVIEW

**Comment by bogdandrutu** [comment]
> Running make update-otel in contrib produces errors like unknown revision pipeline/pipelineprofiles/v0.111.0. I think the larger-than-usual number of modules we're creating this release is making this issue stand out.

After we do the release this is not a problem correct? So then why not doing the release?

**Comment by evan-bradley** [comment]
The [first step](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/release.md#releasing-opentelemetry-collector) in the releasing document says to run this to check for errors. You're right that this shouldn't be a problem after the release, but this is my first release, so I'm looking to play it safe and double-check before releasing core.

**Comment by bogdandrutu** [comment]
I understand, but I am confused about changes to `go.opentelemetry.io/collector/consumer`

**Comment by evan-bradley** [comment]
`go.opentelemetry.io/collector/consumer/consumererror` was made its own module, but `go.opentelemetry.io/collector/consumer@v0.111.0` includes `go.opentelemetry.io/collector/consumer/consumererror` as a package. `go.opentelemetry.io/collector/consumer/consumererror` then becomes an ambiguous import because it can come from the package inside of consumer or from its own module. Therefore I had to update consumer to a version that doesn't include the `go.opentelemetry.io/collector/consumer/consumererror` package.

**Review by sfc-gh-bdrutu — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
