### PR TITLE
Enable best effort serve by default of Prometheus Exporter

### PR DESCRIPTION
**Pull request by liamawhite**
Upgrade to latest github.com/orijtech/prometheus-go-metrics-exporter.

`go get -u github.com/orijtech/prometheus-go-metrics-exporter`

See https://github.com/orijtech/prometheus-go-metrics-exporter/pull/6 for background.

Signed-off-by: Liam White <liam@tetrate.io>

### CODE REVIEW

**Comment by pjanotti** [comment]
@liamawhite could you please also run `go mod tidy`?

**Comment by pjanotti** [comment]
@liamawhite could you please rebase?

**Comment by bogdandrutu** [comment]
Please rebase again :( sorry

**Comment by pjanotti** [comment]
Thanks @liamawhite - sorry for the multiple rebases

**Pull request merged**
