### PR TITLE
expandStringValues function support to map[string]interface{}

### PR DESCRIPTION
**Pull request by kilingzhang**
**Description:** 

The use and expansion of environment variables is supported in the Collector configuration. For example:

```
processors:
  attributes/example:
    actions:
      - key: "${DB_KEY}"
        action: "${OPERATION}"
```

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@kilingzhang consider to add a test to prove that this is needed. See https://github.com/open-telemetry/opentelemetry-collector/pull/4649 where I explicitly added tests to prove that is not needed, maybe I missed something, but would be good to have a unit tests for that.

**Comment by bogdandrutu** [comment]
Pressed by mistake closed instead of comment sorry.

**Comment by kilingzhang** [comment]
> @kilingzhang consider to add a test to prove that this is needed. See #4649 where I explicitly added tests to prove that is not needed, maybe I missed something, but would be good to have a unit tests for that.

ok . I added some tests to prove it was necessary .

**Review by bogdandrutu — APPROVED** [review]
Good fix. Thanks

**Comment by bogdandrutu** [comment]
Can you please rebase (resolve merge conflicts)?

**Review by codeboten — APPROVED** [review]

**Pull request merged**
