### PR TITLE
Move tightly coupled types to the same file

### PR DESCRIPTION
**Pull request by rakyll**
Go is more flexible than other languages and allows tightly coupled types to be in the same file. This makes it easier to read code without having to switch back and forth among different files.

### CODE REVIEW

**Comment by rakyll** [comment]
`make lint` succeeds for me and I cannot see what's failing from CI because logs are not visible to me.

**Review by bogdandrutu — COMMENTED** [review]
I understand this change, but I am concerned about consistency. We use this pattern of config + factory files in all the components. So we either do it everywhere or not do it at all.

All components usually have three files config, factory, {component}. How do you think the structure should look like?

**Comment by rakyll** [comment]
@bogdandrutu I disagree that all of these changes need to go in the same PR. The split really hurts the readability here because factory and config are very tiny files. In packages where they is more going both for config and factory, they could be separate packages. We need to make that judgement case by case.

**Comment by rakyll** [comment]
Friendly ping.

**Comment by bogdandrutu** [comment]
> @bogdandrutu I disagree that all of these changes need to go in the same PR. The split really hurts the readability here because factory and config are very tiny files. In packages where they is more going both for config and factory, they could be separate packages. We need to make that judgement case by case.

@rakyll I am not saying that change must go in one PR. But I was suggesting you to look into the other components and give feedback if we should change (in the future) everywhere this. In almost all the components config and factory are small files.

I have some questions:
1. What about tests? Should they be merged as well?
2. If I understand correctly your logic here, if small files/structs then we should merge, otherwise keep them split. Is that correct?

**Comment by tigrannajaryan** [comment]
+1 to the argument for being consistent across components. Keep in mind that some components have less trivial configs and factories and separate files arguably preferable in such cases (e.g. https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/exporter/signalfxexporter).
I am not sure overall if applied consistently this change will be an improvement for the entire codebase.

**Comment by rakyll** [comment]
@bogdandrutu Sorry that I misunderstood. I can definitely do that. Go doesn't really set any hard rules on splitting or merging things. It encourages you to put things together if you will read them together to avoid context switch. A file with 2000 lines is also hard to read because you'd constantly scroll up and down, that's why we start splitting things when things get large.

Tests can be in their separate files. It's unlikely that config and factory tests needs to be read together.  And the test files are extremely large.

This is not a critical change. Maybe I can spend a week filing and sending few readability improvements at some point. Let me close this for now.

**Pull request closed without merging**
