### PR TITLE
Add Scheme to MapProvider interface

### PR DESCRIPTION
**Pull request by bogdandrutu**
This is another required step in order to support configuring map providers via the Builder.

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/4759

This is a breaking change, since adds a new func to an interface. It is hard to make this backwards compatible, and would like to move forward with this exception.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]
LGTM, I find this to be an acceptable breakage of the rules (but would like to hear from at least one other approver)

**Review by dmitryax — APPROVED** [review]

**Comment by dmitryax** [comment]
Seems reasonable to me as well

**Comment by tigrannajaryan** [comment]
Does `Scheme()` need to be part of `MapProvider` interface? I see an analogy with components where we made `Type` part of the component factory, not of the component instance itself. Using this same approach we can introduce factories that would then allow creating `MapProvider`s in MustNewDefaultConfigProvider.

**Comment by bogdandrutu** [comment]
> I see an analogy with components where we made Type part of the component factory, not of the component instance itself.

I have a different view of this, kind of the `MapProvider` is the equivalent of the `Factory` and the `Retrieved` value is the component.

**Comment by tigrannajaryan** [comment]
> > I see an analogy with components where we made Type part of the component factory, not of the component instance itself.
> 
> I have a different view of this, kind of the `MapProvider` is the equivalent of the `Factory` and the `Retrieved` value is the component.

Yeah, I guess that works too. The factory-based approach would probably be a bit more uniform with what we do with components from naming perspective, but I think your approach is fine too.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
