### PR TITLE
Revert "Bump jaeger version with thrift 0.13 (#1203)"

### PR DESCRIPTION
**Pull request by tigrannajaryan**
This reverts commit 1e6596b144d09a1f3129f7cdd5eb334da65519d3.

Reverting because it prevents Contrib from building and blocks
the release.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@pavolloffay Sorry, I had to revert https://github.com/open-telemetry/opentelemetry-collector/pull/1203 which made the Contrib build fail and blocked the release.

**Comment by nilebox** [comment]
@tigrannajaryan could you please share more details on what specifically broke the contrib build / what was the failure message?

**Comment by pavolloffay** [comment]
+1 I guess it's because https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/master/receiver/jaegerlegacyreceiver/trace_receiver.go#L59 which uses tchannel.

**Comment by pavolloffay** [comment]
PR to remove the tchannel receiver from OTEL contrib https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/397

**Pull request merged**
