### PR TITLE
Update images in Design doc

### LINKED ISSUE #2781: Fix TODOs in Design doc
**Describe the bug**
[Design  doc](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/design.md) has some TODOs which needs to be fixed. Most of the images need to reflect the text description.

**Steps to reproduce**
-

**What did you expect to see?**
Updated images matching the text documentation.

**What did you see instead?**
Mismatch in the text and the related image.

**What version did you use?**
-

**What config did you use?**
-

**Environment**
-

**Additional context**
-

### LINKED ISSUE #2817: Add instructions on how to update images in "CONTRIBUTION.md"
/cc sitaramshelke

https://github.com/open-telemetry/opentelemetry-collector/pull/2801#issuecomment-807898781

### PR DESCRIPTION
**Pull request by sitaramshelke**
**Description:**
Updated the images in the Design doc to match with the description surrounding it.

**Link to tracking Issue:**
Fixes #2781 
Fixed #2817

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@sitaramshelke what did you use to generate this pictures? Can we get access to the source so we can easily change them in the future? Maybe add a link to the source?

**Comment by sitaramshelke** [comment]
@bogdandrutu I used [Excalidraw](https://excalidraw.com/) (Free and OSS!). I also exported the PNG with the "scene information" which allows importing the PNG in an editable form. 
Now that you've approved the changes I'll squash these multiple commits into one and add the steps to edit the image in the commit description. Will that be sufficient?

**Comment by bogdandrutu** [comment]
Please add a note at the end of the document about that website :), or maybe in "CONTRIBUTION.md". I am confident that I will forget about it.

**Comment by bogdandrutu** [comment]
Need to pass lint:

```
./CONTRIBUTING.md:292:115: "applicaton" is a misspelling of "application"
./CONTRIBUTING.md:292:365: "contributers" is a misspelling of "contributors"
```

**Pull request merged**
