### PR TITLE
Move all utils configmapproviders to internal to prepare interface change

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Comment by alolita** [comment]
@bogdandrutu This is a pretty significant breaking change for downstream distributions such as AWS Distro for OpenTelemetry. We should've had community discussions and reviews from other approvers before making these changes. Same with https://github.com/open-telemetry/opentelemetry-collector/pull/4636

**Comment by Aneurysm9** [comment]
Exported identifiers that are made internal by this change (in addition to the not-at-all-unused `InMemory` provider removed in https://github.com/open-telemetry/opentelemetry-collector/pull/4507) are [in use by the ADOT collector](https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/config/config_factory.go#L33-L38).

**Comment by bogdandrutu** [comment]
@Aneurysm9 if you have reviewed the #4507 which was open for 2 weeks probably you could have seen that, but lucky for you I did implement what ADOT needs in #4574.

So I am not sure where is the breaking change.

**Comment by jcchavezs** [comment]
Moving NewExpand into an internal package is indeed a significant breaking change and I am not sure if there is a way back to this. Could you please at least link why this happened?

**Comment by Aneurysm9** [comment]
@jcchavezs #4672 seeks to address this.  Please weigh in there.

**Pull request merged**
