### PR TITLE
Change call pattern for scraper

### PR DESCRIPTION
**Pull request by humivo**
**Description:** Change obsreport helpers for scraper to use the same pattern as Processor/Exporter and modified existences in the code.

**Link to tracking Issue:** [Issue #3313](https://github.com/open-telemetry/opentelemetry-collector/issues/3313)

### CODE REVIEW

**Comment by alolita** [comment]
@Aneurysm9 @dashpole can you please review?

**Review by Aneurysm9 — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Comment by alolita** [comment]
@bogdandrutu this PR is ready to be merged.

**Comment by tigrannajaryan** [comment]
Please resolve the conflict.

**Review by tigrannajaryan — APPROVED** [review]

**Comment by alolita** [comment]
@humivo can you please resolve this conflict so that this PR can be merged?

**Comment by alolita** [comment]
@bogdandrutu @tigrannajaryan  can you please merge? So that the related issue can be closed. Ty!

**Pull request merged**
