### PR TITLE
Update koanf to v2

### PR DESCRIPTION
**Pull request by dbason**
This PR updates the koanf dependency to v2

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Is this addressing an issue or limitation with the older koanf library?

**Comment by mx-psi** [comment]
@knadh If you have the time, can you help us understand what changed between koanf v1 and v2 and what would be the benefits and changes if we update?

**Comment by knadh** [comment]
Hi @mx-psi. Functionally, no changes. The package structure has changed where every provider/parser has become its own module (with its own go.mod) to become a one repository-many modules system.

**Benefits:**
This removes references to all indirect dependencies in the main go.mod significantly de-cluttering it. These would never be compiled into the build, but `go get .../koanf` would still pull them in the dev environment in v1. Check out the main package's [go.mod](https://github.com/knadh/koanf/blob/master/go.mod) in v2.

It is safe (and also easy) to upgrade to v2 as it is functionally identical to v1. While this needn't be done on priority, I would recommend moving to v2 as that is where any continued improvements will land. v1 is frozen and will only receive security updates.

**Review by codeboten — COMMENTED** [review]
Thanks for the explanation @knadh!

**Review by codeboten — COMMENTED** [review]
Please run `make gotidy` to tidy up the dependencies

**Comment by dbason** [comment]
I suspect the tests failed due to the github outage.

**Comment by codeboten** [comment]
Needs one more `make crosslink && make gotidy`... not sure why crosslink included a bunch of imports in a previous commit

**Comment by dbason** [comment]
I've done that now and squashed into the last commit

**Review by codeboten — APPROVED** [review]
Thanks it's looking good now

**Pull request merged**
