### PR TITLE
Generate OTLP Go code in this repositorry

### PR DESCRIPTION
**Pull request by tigrannajaryan**
Generate ProtoBufs in this repository instead of importing from opentelemetry-proto.
This allows us to customize the generation process.

- Added opentelemetry-proto as a submodule.
- Added `make genproto` target that generates Go ProtoBufs from opentelemetry-proto
  submodule and puts them in internal/opentelemetry-proto-gen.
  Generation is done using Gogoproto instead of Go Protobuf.
- Modified all files to import OTLP Go code from internal/opentelemetry-proto-gen.

### CODE REVIEW

**Comment by owais** [comment]
Could this make life harder for a project that imports collector and generated Go code from the proto repo both in the same project? Trying to think if this will make consuming the generated code from the proto repo harder/weirder in any cases.

**Comment by owais** [comment]
Will generated code `github.com/open-telemetry/opentelemetry-proto/gen` remain active for the community to import and use in other projects?

**Comment by tigrannajaryan** [comment]
> Could this make life harder for a project that imports collector and generated Go code from the proto repo both in the same project? Trying to think if this will make consuming the generated code from the proto repo harder/weirder in any cases.

@owais They probably should not do this, but I cannot think of problems. From compilers perspective these 2 completely incompatible sets of generated structs and functions. There will be no way to mix the 2. The 2 obviously will be compatible on the wire in the serialized form, so technically one project may import both and use simultaneosuly (e.g. we can have tests that verify that serialized wire format is indeed the same).

I may need to move generate code from `internal` package to a public package so that "contrib" components can use it if needed. Not sure if it is needed yet.

**Comment by owais** [comment]
I'm not sure but I think importing even separate structs that implement the same proto definition doesn't go well with the protobuf implementation as it has a global registry for structs. So two structs trying to register as the same protobuf message might cause problems. Again, I'm not sure how big of a problem this is or even if it is a problem in the first place. Just concerned we might make life very hard for others. I had similar issues with dealing with Jaeger proto in the past.

**Comment by tigrannajaryan** [comment]
>as it has a global registry for structs

Ah, I didn't know this. Let me play with it a bit.

**Comment by bogdandrutu** [comment]
@owais @tigrannajaryan I think the registry is per generated class, as long as the classes are generated in one place I don't think it should be a problem.

**Comment by tigrannajaryan** [comment]
@owais I just added a test that uses both goproto and gogoproto messages (and verifies wire compatibility). This seems to be running fine. Any other scenarios which I should be worried about?

**Comment by tigrannajaryan** [comment]
Don't merge yet. I _think_ the latest commit resulted in slower performance (uses wrong ProtoBuf implementation?). I need to check.

**Comment by tigrannajaryan** [comment]
However, please continue reviewing the PR.

**Comment by tigrannajaryan** [comment]
OK, I cannot see any discernible performance difference (any differences are below measurement error).

**Comment by owais** [comment]
I tested locally by building a custom collector that imports your branch and also using opentelemetry-proto and did not see any double registration warnings/errors so I suppose this is good to go. 👍

**Comment by tigrannajaryan** [comment]
@owais can I get an approval?

**Comment by tigrannajaryan** [comment]
@bogdandrutu do you want to review or good to merge?

**Comment by nilebox** [comment]
Is the plan to do the same in `opentelemetry-go` and delete generated Go code from `opentelemetry-proto`?

**Comment by tigrannajaryan** [comment]
> Is the plan to do the same in `opentelemetry-go` and delete generated Go code from `opentelemetry-proto`?

No such plans for now. This enables us to decouple Collector's code generation from the rest, since Collector may make different choices. In Collector we may be willing to have a bit more complicated code with custom data types in order to gain performance. `opentelemetry-go` may not be willing to make the same compromise.

**Pull request merged**
