### PR TITLE
[connector,exporter,receiver,extension,processor] remove deprecated funcs/structs

### PR DESCRIPTION
**Pull request by codeboten**
Finishing CreateSettings rename.

### CODE REVIEW

**Comment by codeboten** [comment]
Blocked by https://github.com/open-telemetry/opentelemetry-collector/issues/10447

**Comment by mx-psi** [comment]
I think this is no longer blocked, right?

**Comment by mx-psi** [comment]
```
# github.com/open-telemetry/otel-arrow/collector/netstats
Error: /home/runner/go/pkg/mod/github.com/open-telemetry/otel-arrow/collector@v0.24.0/netstats/netstats.go:138:51: undefined: exporter.CreateSettings
Error: /home/runner/go/pkg/mod/github.com/open-telemetry/otel-arrow/collector@v0.24.0/netstats/netstats.go:173:51: undefined: receiver.CreateSettings
```

**Comment by codeboten** [comment]
@mx-psi pulled in the PR that removed the dependency. will see if it passes the CI now

**Review by mx-psi — APPROVED** [review]
It did! :rocket:

**Pull request merged**
