### PR TITLE
Add private method to GrpcServer interface, disallow direct implementation

### PR DESCRIPTION
**Pull request by bogdandrutu**
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6966

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
Looks good, but aren't there any implementations of it in this project? Not even as tests?

**Comment by bogdandrutu** [comment]
> Looks good, but aren't there any implementations of it in this project? Not even as tests?

They are, but I did it in 2 steps (as suggested). Last release I added the "Unimplemented*", used it, and add a comment to embed it (since cannot use deprecation notice). Then now I am enforcing that :)

**Comment by bogdandrutu** [comment]
@mx-psi let me know when you fix DD :)

**Comment by mx-psi** [comment]
I will try to get the DD fix done today and updated on contrib by Monday :)

**Comment by mx-psi** [comment]
open-telemetry/opentelemetry-collector-contrib/pull/18074 will unblock this

**Pull request merged**
