### PR TITLE
setup OSSF Scorecard workflow

### PR DESCRIPTION
**Pull request by mmorel-35**
**Description:** setup OSSF Scorecard workflow
This will help identify and fix vulnerabilities. 

[OpenSSF Scorecard](https://securityscorecards.dev/viewer/?uri=github.com/open-telemetry/opentelemetry-collector)

### CODE REVIEW

**Review by codeboten — APPROVED** [review]
Thanks @mmorel-35!

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
Will put a reminder to merge this next week, I think that's better to avoid issues in the release process

**Comment by mx-psi** [comment]
@mmorel-35 can you fix the conflicts?

**Comment by mx-psi** [comment]
This does not modify the contrib test workflow so I am going to skip the tests and merge

**Pull request merged**
