### PR TITLE
Add profiles support to OTLP exporter

### PR DESCRIPTION
**Pull request by dmathieu**
#### Description

This uses the profiles internal packages that were implemented in previous PRs to provide profiles support to the OTLP exporter.

This PR requires #11226✅  to be merged first.

### CODE REVIEW

**Comment by mx-psi** [comment]
I merged #11226 :)

**Review by mx-psi — APPROVED** [review]
LGTM. @open-telemetry/collector-approvers I will merge this on Friday EU morning unless there are comments before then

**Comment by mx-psi** [comment]
@dmathieu Can you fix the merge conflict?

**Comment by dmathieu** [comment]
Done!

**Pull request merged**
