### PR TITLE
Disable process scraper for any non Linux/Windows OS

### PR DESCRIPTION
**Pull request by james-bebbington**
Much of the process scraper functionality is not supported on non Linux/Windows OSs, or is implemented poorly, e.g. this was taking about 15s to complete on my Macbook. Have opted to explicitly disable the scraper on any other OS.

Also fixed issue where an error wasn't returned on initialization in one case and added a test for this.

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/958

### CODE REVIEW

**Comment by james-bebbington** [comment]
This is the highest I can possibly get coverage for this PR since coverage reports are Linux only

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by bogdandrutu** [comment]
I closed this by mistake

**Comment by james-bebbington** [comment]
The build checks don't seem to be getting triggered, do I need to recreate this PR since it was closed?

**Pull request merged**
