### PR TITLE
Fix port number in jaegerreceiver/README.md

### PR DESCRIPTION
**Pull request by cocotyty**

### CODE REVIEW

**Comment by cocotyty** [comment]
@bogdandrutu

**Comment by bogdandrutu** [comment]
Please sign the CLA 👍

**Comment by cocotyty** [comment]
> Please sign the CLA 👍

done

**Comment by cocotyty** [comment]
@bogdandrutu

**Review by bogdandrutu — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Comment by jpkrohling** [comment]
Just wanted to record that having `insecure: true` leaves a really bad aftertaste. We'll need to go over the documentation and start it with a "here's how to generate certs" step, and use those certs everywhere, to avoid `insecure: true`. Otherwise, people will end up using that in production, defeating the purpose of having the communication secure by default.

**Comment by bogdandrutu** [comment]
@cocotyty ping

**Comment by bogdandrutu** [comment]
A rebase is needed 👍

**Pull request merged**
