### PR TITLE
[configtls] mark module as stable

### LINKED ISSUE #9377: Stabilize module configtls
Before stabilizing a module, an approver or maintainer must make sure that the following criteria have been met for at least two successive minor version releases:

- [x] No open issues or PRs in the module that would require breaking changes
- [x] No TODOs in the module code that would require breaking changes
- [x] No deprecated symbols in the module
- [x] No symbols marked as experimental in the module
- [x] The module follows the [Coding guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md)

Please also make sure to publicly announce our intent to stabilize the module on:

- [x] The #otel-collector CNCF Slack Channel
- [x] The #opentelemetry CNCF Slack channel
- [x] A Collector SIG meeting (if unable to attend, just add to the agenda)

To help other people verify the above criteria, please link to the announcement and other links used to complete the above in a comment on this issue.

Once all criteria are met, close this issue by moving this module to the `stable` module set.

### PR DESCRIPTION
**Pull request by atoulme**
#### Description
Mark module as stable.

#### Link to tracking issue
Fixes #9377

### CODE REVIEW

**Comment by codeboten** [comment]
Reviewing this PR inspired https://github.com/open-telemetry/opentelemetry-collector/pull/10358

**Comment by atoulme** [comment]
Thank you @codeboten , indeed the dependency on confmap was only through tests.

**Review by mx-psi — APPROVED** [review]
I support this:

- No explicit or implicit dependencies on unstable modules (other than via the fact that this has `mapstructure` tags)
- No 1.0 issues remaining in the tracker
- No experimental or TODO symbols
- Structs follow correct naming and methods have `context.Context` on them

cc @open-telemetry/collector-approvers

**Review by songy23 — APPROVED** [review]

**Comment by codeboten** [comment]
@mx-psi @songy23 @atoulme  One thing to keep in mind is that this package does expose `mapstructure` tags for the struct, which would mean that we'd have to keep support for them around for the life of this package. Is this ok? @TylerHelmuth reminded me that this was the reason we'd held on stabilizing other config packages until confmap is stable

**Comment by mx-psi** [comment]
@codeboten Right, I forgot about this. I don't see us changing `mapstructure` tags for something else but it makes sense to discuss explicitly. Should we file an issue about this?  (We don't have one, do we?)

**Comment by codeboten** [comment]
@mx-psi i think only issue that comes close is this one around how mapstructure is unmarshaled https://github.com/open-telemetry/opentelemetry-collector/issues/9532, i don't know if we want another issue that specific talks about which tags should be supported moving forward?

**Comment by atoulme** [comment]
Is changing tags on a struct field a breaking change? The go API is unchanged, right?

**Comment by codeboten** [comment]
@atoulme it's currently listed in versioning.md as breaking change https://github.com/open-telemetry/opentelemetry-collector/blob/main/VERSIONING.md#configuration-structures

**Comment by mx-psi** [comment]
We had some discussion about bumping `MinTLS` to 1.3. I think this is something that is not a breaking change given that the Go team themselves have proposed changes of this sort in the past (see golang/go#45428) and this being considered a security best practice.

I am not sure how we should best clarify this on `VERSIONING.md`, but I think this can be dealt with independently from this PR and that we can merge this now.

**Pull request merged**
