### PR TITLE
[chore] remove deprecated code

### PR DESCRIPTION
**Pull request by codeboten**

### CODE REVIEW

**Comment by dmitryax** [comment]
@codeboten PTAL https://github.com/open-telemetry/opentelemetry-collector/pull/6170

**Comment by codeboten** [comment]
Thanks @dmitryax! Yes i saw your PR and realized after submitting this one that it wont pass until yours is merged

**Comment by bogdandrutu** [comment]
Please rebase.

**Comment by bogdandrutu** [comment]
@codeboten you need to also remove the tests for the deprecated funcs. @dmitryax loves to leave them behind :))

**Comment by dmitryax** [comment]
Haha I just don't like to see dropped coverage :)

**Comment by codeboten** [comment]
@bogdandrutu @dmitryax yup... on it :)

**Comment by codeboten** [comment]
Contrib tests are failing, there is a bunch of work underway to address the issues:

https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/14600
https://github.com/DataDog/datadog-agent/pull/13684
https://github.com/influxdata/influxdb-observability/pull/115
https://github.com/GoogleCloudPlatform/opentelemetry-operations-go/pull/489

**Comment by codeboten** [comment]
All the contrib dependencies have been updated now, this is ready to merge when approved 👍🏻

**Review by dmitryax — APPROVED** [review]
Thanks @codeboten!

**Pull request merged**
