### PR TITLE
[chore] remove unused opencensus code 

### PR DESCRIPTION
**Pull request by codeboten**
Follows https://github.com/open-telemetry/opentelemetry-collector/pull/9102

### CODE REVIEW

**Comment by bogdandrutu** [comment]
I think this needs to be merged after we remove the gate. So 3-4 versions?

**Comment by codeboten** [comment]
> I think this needs to be merged after we remove the gate. So 3-4 versions?

@bogdandrutu correct, this PR is after https://github.com/open-telemetry/opentelemetry-collector/pull/9102 which will be merged after v0.92.0 is released

**Review by atoulme — APPROVED** [review]
Nice PR, lots of code going away :)

**Review by dmitryax — APPROVED** [review]
Nice! 🎉 

We can also remove `goleak.IgnoreTopFunction("go.opencensus.io/stats/view.(*worker).start")` from the goleak tests now :)

**Review by TylerHelmuth — APPROVED** [review]
Exciting!

**Pull request merged**
