### PR TITLE
[chore] Remove prometheus need to check test metrics in componenttest

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
i love this idea, will need to do a full review but i think it makes sense to remove. are there still e2e tests that validate the output from the service?

**Comment by bogdandrutu** [comment]
> i love this idea, will need to do a full review but i think it makes sense to remove. are there still e2e tests that validate the output from the service?
Yes in https://github.com/open-telemetry/opentelemetry-collector/blob/main/service/service_test.go

**Comment by bogdandrutu** [comment]
@codeboten ping :)

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
```
/home/runner/work/opentelemetry-collector/opentelemetry-collector/.tools/golangci-lint run
Error: componenttest/otelchecker.go:131:49: `unknwon` is a misspelling of `unknown` (misspell)
		return metricdata.DataPoint[N]{}, fmt.Errorf("unknwon metric type: %T", a)
```

**Pull request merged**
