### PR TITLE
Add cpu utilization metric to cpu scraper

### PR DESCRIPTION
**Pull request by james-bebbington**
Added cpu utilization metric (computed from cpu times) to the cpu scraper / hostmetricsreceiver.

### CODE REVIEW

**Comment by james-bebbington** [comment]
> I am confused about this. I think I discussed this with someone, and we decided to go with 2 metrics `cpu/time` and `cpu/available` and if needed backend or user can compute utilization from these metrics.
> 
> I think we should do that way.

By `cpu/available`, do you mean the number of cores available? Technically I don't think we would need that either as its already implicit in the data - since we report cpu usage per core. Utilization could be computed on the backend from something like `rate(sum(cpu_time{non-idle states}) / sum(cpu_time{all states}))`, similar to what this PR is doing in the code (and then `avg` over the cpu core dimension if desired).

But since cpu utilization is such a commonly desired metric, it seems like there's still potentially value in precomputing this in addition to the cpu time metric, rather than leaving it to the user to perform a non-trivial calculation. I didn't understand your point in the [Host Metrics doc](https://docs.google.com/document/d/1i-QG-TxkIWVbdx86UM2GXcFvpeCV7zSBsPmMyMkOEBk/edit?disco=AAAAGdMhb1Q) about it being hard to reverse the calculation?

As a side note, a lot of performance counter data reported from Windows is already pre-computed as a rates or utilizations, so when getting, for example, per process cpu data, the most straightforward and performant way to get this data on Windows will likely require this to be expressed as utilizations only.

I'll check-in with a few other people internally to get their thoughts on if we need this metric, but I'd be interested to get anyone else's opinions on this one as well.

**Comment by bogdandrutu** [comment]
@james-bebbington not completely against this, but we should have at least a mechanism to disable this metric.

**Comment by bogdandrutu** [comment]
Please rebase and fix conflicts.

**Comment by james-bebbington** [comment]
Going to close this one for now, I may come back to it later, but it's likely not required

**Pull request closed without merging**
