### PR TITLE
[chore] prepare release 0.57.2

### PR DESCRIPTION
**Pull request by jpkrohling**
Prepare for v0.57.2

### CODE REVIEW

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
Missing go.mod changes to update to 0.57.2

**Comment by bogdandrutu** [comment]
Also in every go.mod that we release add at the bottom:

```
retract v0.57.0 // Reason
retract v0.57.1 // Reason
```

**Comment by jpkrohling** [comment]
Done!

**Comment by jpkrohling** [comment]
Note that I have changed the destination for this PR, from `main` to the release branch. Let me know if I should revert this.

**Review by codeboten — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
