### PR TITLE
Add kafkametrics receiver

### PR DESCRIPTION
**Pull request by dshomoye**
**Description:** This is the first PR for the introduction of a kafkametrics receiver for open-telemetry. This sets up the config structure and high level layout of the receiver. 
Kafka metrics falls under the "5 min to value" section of the roadmap for [application-specific metric collection](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/roadmap.md#long-term-roadmap).

The receiver is set up to *scrape* from kafka at a user provided interval (default is every minute). 
Scrapers are divided up by kafka-specific entities (topics, consumers and brokers, for now).

**Testing:** Unit tests have been added for the skeleton code added; additional tests for concrete implementation are still on going. Subsequent PRs will include details of tests performed.

**Documentation:** There is a README describing how to configure the receiver. The general documentation for receivers has not yet been updated as the current implementation is not yet functional/usable.

### CODE REVIEW

**Review by bogdandrutu — COMMENTED** [review]
Please follow https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component

**Comment by dshomoye** [comment]
> Please follow https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md#when-adding-a-new-component

Thanks for pointing that out, I somehow misinterpreted that paragraph. I've update to only include the basic factory and receiver files.

**Comment by tigrannajaryan** [comment]
I am not sure this repository is the right place for this component. I think contrib may be a better place. Generally, we are looking at moving components from this repo to contrib, not adding more components to the core. This is to prepare for the GA release which will only include a small number of core components initially: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/ga-roadmap.md

I advise to close this PR and submit new PRs in the contrib while following the contributing guide.

**Comment by dshomoye** [comment]
> I am not sure this repository is the right place for this component. I think contrib may be a better place. Generally, we are looking at moving components from this repo to contrib, not adding more components to the core. This is to prepare for the GA release which will only include a small number of core components initially: https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/ga-roadmap.md
> 
> I advise to close this PR and submit new PRs in the contrib while following the contributing guide.

thank you! I will close it now and move to the contrib repo.

**Pull request closed without merging**
