### PR TITLE
Add grpc creations test case to jaeger receiver

### PR DESCRIPTION
**Pull request by huikang**
- increase test coverage

Signed-off-by: Hui Kang <kangh@us.ibm.com>

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Please add an issue to fix the failing test if no such issue already exists.

**Comment by huikang** [comment]
@tigrannajaryan , the issue seems related to https://github.com/open-telemetry/opentelemetry-collector/issues/41

**Comment by pjanotti** [comment]
@huikang something went wrong with CI could you please amend the commit and force push to rebuild it? Thanks.

**Comment by huikang** [comment]
> @huikang something went wrong with CI could you please amend the commit and force push to rebuild it? Thanks.

Done. Thanks.

**Pull request merged**
