### PR TITLE
Prepare patch release v0.90.1

### PR DESCRIPTION
**Pull request by dmitryax**

### CODE REVIEW

**Review by codeboten — CHANGES_REQUESTED** [review]
This needs to be done after the fix has been merged to the branch correct? I'm not seeing the fix in the branch

**Comment by dmitryax** [comment]
I can do it separately tho

**Comment by dmitryax** [comment]
submitted https://github.com/open-telemetry/opentelemetry-collector/pull/9026

**Comment by dmitryax** [comment]
@codeboten @mx-psi the fix is merged separately and this one is rebased. PTAL

**Pull request merged**
