### PR TITLE
[configcompression] Mark as stable

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:**
Mark `configcompression` as Stable

**Link to tracking Issue:** 
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9374

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
cc @open-telemetry/collector-approvers

**Review by codeboten — APPROVED** [review]

**Review by atoulme — APPROVED** [review]
LGTM, checked the code and test coverage.

**Review by evan-bradley — APPROVED** [review]

**Comment by bogdandrutu** [comment]
I would personally prefer to stabilize modules in the order of possible dependencies (see https://github.com/open-telemetry/opentelemetry-collector/issues/9491) and not mark random modules as stable before we have all the basic modules stable.

**Comment by mx-psi** [comment]
@bogdandrutu  This module does not have any explicit dependency to `confmap`, `consumer` or `component`, and I think the only thing we are assuming from these modules is that we will honor the `encoding.TextUnmarshaler` interface when unmarshaling configuration.

I don't see us changing this assumption, since this is a Go stdlib interface, but if you think we may change this or you have a different specific concern, I would want to have an issue for it.

**Review by jpkrohling — APPROVED** [review]

**Review by songy23 — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
