### PR TITLE
[processorhelper] Fix bug where record in/out metrics were skipped

### LINKED ISSUE #11351: Processor In/Out metrics not recorded if process func fails (even for skipping next component)
See https://github.com/open-telemetry/opentelemetry-collector/blob/main/processor/processorhelper/metrics.go#L56

### PR DESCRIPTION
**Pull request by djaglowski**
Resolves #11351

### CODE REVIEW

**Comment by djaglowski** [comment]
The contrib test failure appears to be expected with this change. The filter processor returns `ErrSkipProcessingData` if it filtered all data points, which happens in the test. Previously this caused a single data point to _not_ be counted as incoming.

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
There are lint issues.

**Comment by dmitryax** [comment]
@djaglowski do you have a fix for the tests on contib side by chance?

**Comment by djaglowski** [comment]
I'll update core and make the fix.

**Pull request merged**
