### PR TITLE
[chore] use multimod diff

### LINKED ISSUE #8012: Unable to run make check-change
As part of the v0.81.0/v1.0.0-rcv0014 release, I ran the `make check-change` target but ran into multiple issues. Here is a copy of the output on my terminal:

```sh
❯ make check-changes PREVIOUS_VERSION=v1.0.0-rcv0013 MODSET=stable
make: Nothing to be done for 'check-changes'.

❯ make -B check-changes PREVIOUS_VERSION=v1.0.0-rcv0013 MODSET=stable
mkdir -p /home/pablo.baeyens/Source/otel/opentelemetry-collector/.tools
cd /home/pablo.baeyens/Source/otel/opentelemetry-collector/internal/tools && go build -o /home/pablo.baeyens/Source/otel/opentelemetry-collector/.tools/yq -trimpath github.com/mikefarah/yq/v4

❯ make -B check-changes PREVIOUS_VERSION=v1.0.0-rcv0013 
mkdir -p /home/pablo.baeyens/Source/otel/opentelemetry-collector/.tools
cd /home/pablo.baeyens/Source/otel/opentelemetry-collector/internal/tools && go build -o /home/pablo.baeyens/Source/otel/opentelemetry-collector/.tools/yq -trimpath github.com/mikefarah/yq/v4

❯ make -B check-changes MODSET=stable
mkdir -p /home/pablo.baeyens/Source/otel/opentelemetry-collector/.tools
cd /home/pablo.baeyens/Source/otel/opentelemetry-collector/internal/tools && go build -o /home/pablo.baeyens/Source/otel/opentelemetry-collector/.tools/yq -trimpath github.com/mikefarah/yq/v4
PREVIOUS_VERSION not defined
usage: make check-changes PREVIOUS_VERSION=<version eg 0.52.0> MODSET=beta
exit 1
make: *** [Makefile:444: check-changes] Error 1
```

To summarize the issues found:

1. The target is not identified as 'phony', so I have to force running it with `-B`
2. The target does not seem to do anything if I pass the (pressumably) correct inputs
3. The target does not fail if I omit `MODSET`, but does if I omit `PREVIOUS_VERSION`

If I remove the `ifndef` checks I can get some output (using `NORMALIZED_PREVIOUS_VERSION` instead of `PREVIOUS_VERSION` instead):

```
make -B check-changes NORMALIZED_PREVIOUS_VERSION=v1.0.0-rcv0013 MODSET=stable
mkdir -p /home/pablo.baeyens/Source/otel/opentelemetry-collector/.tools
cd /home/pablo.baeyens/Source/otel/opentelemetry-collector/internal/tools && go build -o /home/pablo.baeyens/Source/otel/opentelemetry-collector/.tools/yq -trimpath github.com/mikefarah/yq/v4
No stable modules have changed since v1.0.0-rcv0013
No need to release stable.
make: *** [Makefile:436: check-changes] Error 1
```

I am using GNU make 4.3:

```
❯ make --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

### PR DESCRIPTION
**Pull request by codeboten**
The logic from `check-changes` was moved to multimod diff.

Fixes #8012

### CODE REVIEW

**Comment by codeboten** [comment]
Depends on https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/350

**Review by mx-psi — COMMENTED** [review]
LGTM, should we do a release on opentelemetry-go-build-tools first though?

**Comment by codeboten** [comment]
@mx-psi sure, here's the PR https://github.com/open-telemetry/opentelemetry-go-build-tools/pull/361

**Comment by codeboten** [comment]
> LGTM, should we do a release on opentelemetry-go-build-tools first though?

bumped to v0.9.0

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
