### PR TITLE
Replace Parser.MergeStringMap with more generic Parser.Merge

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please review @codeboten

**Review by codeboten — COMMENTED** [review]
Change looks good, please resolve the conflict.

**Comment by bogdandrutu** [comment]
@codeboten PTAL

**Review by codeboten — APPROVED** [review]
Thanks for fixing 👍

**Pull request merged**
