### PR TITLE
Put HTTP headers into context in Jaeger Thrift receiver

### PR DESCRIPTION
**Pull request by pavolloffay**
Signed-off-by: Pavol Loffay <p.loffay@gmail.com>

**Description:**

Put HTTP headers in Jaeger receiver into context object. I need to access haeders in a custom processor to attach tenant ID into span attributes and calculate some metrics.

Also https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/master/processor/routingprocessor uses metadata to access tenant ID header.

**Link to tracking Issue:** <Issue number if applicable>

Resolves https://github.com/open-telemetry/opentelemetry-collector/issues/2401

### CODE REVIEW

**Comment by pavolloffay** [comment]
@bogdandrutu @tigrannajaryan could you please review?

**Comment by pavolloffay** [comment]
FYI in the meantime, we have applied the patch to our fork to unblock us https://github.com/hypertrace/hypertrace-collector/pull/23. It would be great to move this PR to decrease maintenance pain.

**Review by bogdandrutu — COMMENTED** [review]
Not sure which headers do you need access to, but there are some information we add related to tenant id (https://github.com/open-telemetry/opentelemetry-collector/blob/main/client/client.go), also there is this discussion https://github.com/open-telemetry/opentelemetry-collector/pull/2495

The problem with context is that we drop it in processors like batch.

**Comment by pavolloffay** [comment]
> Not sure which headers do you need access to, but there are some information we add related to tenant id

`X-tenant-id` is the header name. Our collector is behind proxy that handles auth and injects this header if the access is allowed. 

> The problem with context is that we drop it in processors like batch.

It's is not an issue for us since we access the headers in the first processor in the pipeline.

**Comment by pavolloffay** [comment]
any update on this @bogdandrutu ?

**Pull request closed without merging**
