### PR TITLE
Remove ErrorWaitingHost from componenttest

### PR DESCRIPTION
**Pull request by bogdandrutu**
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/2540

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by tigrannajaryan — COMMENTED** [review]
Why removing this? It is used by many component tests in the contrib.

**Comment by bogdandrutu** [comment]
@tigrannajaryan do you feel that this is the intent of this helper, I am not sure this is how we want to provide a helper for testing that case. Maybe a refactoring of this class can be done to ensure we expose a minimal API but still valid test helper.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan do you feel that this is the intent of this helper, I am not sure this is how we want to provide a helper for testing that case. Maybe a refactoring of this class can be done to ensure we expose a minimal API but still valid test helper.

I am not sure I understand. What is the plan for contrib components that use this helper? Will you copy/paste this helper in each component?

I may be missing something.

**Comment by bogdandrutu** [comment]
I mean, can you double check and see if the tests actually make sense in the contrib, was thinking as a possibility to remove them. But that may be too aggresive.

**Review by tigrannajaryan — APPROVED** [review]

**Pull request merged**
