### PR TITLE
Remove derprecated NewLogs[Request]Exporter funcs

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@songy23 can you please fix datadog "datadog-agent/comp/otelcol/otlp/components/exporter/logsagentexporter@v0.58.0"?

**Comment by songy23** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/36345 fixes the contrib tests

**Review by songy23 — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@songy23 your fix did not fully fix this, see https://github.com/open-telemetry/opentelemetry-collector/actions/runs/11825085924/job/32948068600?pr=11661

**Comment by songy23** [comment]
I think it's a cache issue, the same CI succeeded in other PRs, see https://github.com/open-telemetry/opentelemetry-collector/pull/11671 https://github.com/open-telemetry/opentelemetry-collector/actions/runs/11825424725/job/32949171213?pr=11671

**Comment by songy23** [comment]
NVM - the CI only fails in this PR because this PR does break datadog exporter https://github.com/open-telemetry/opentelemetry-collector/actions/runs/11825085924/job/32948068600?pr=11661

**Pull request merged**
