### PR TITLE
[confignet] Remove deprecated structs

### PR DESCRIPTION
**Pull request by TylerHelmuth**
**Description:** <Describe what has changed.>
Removes deprecated structs

**Link to tracking Issue:** <Issue number if applicable>
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/9509

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@TylerHelmuth can you fix contrib please?

**Comment by TylerHelmuth** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31354

**Comment by TylerHelmuth** [comment]
Although we need to wait for the Contrib release to finish

**Comment by TylerHelmuth** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/31354 is ready for review

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
