### PR TITLE
Add async exporting for batchprocessor

### PR DESCRIPTION
**Pull request by pkositsyn**
**Description:** 
Fixing a bug - the worker running in batch processor was used to do next consumers stuff. Now it starts a new goroutine for that.

**Link to tracking Issue:** #2248

### CODE REVIEW

**Comment by pkositsyn** [comment]
@bogdandrutu Could you please take a look for this small PR? It solves a critical problem

**Comment by pkositsyn** [comment]
It isn't stale. Can anyone take a look please? @bogdandrutu @tigrannajaryan

**Comment by pkositsyn** [comment]
Still trying to make it not stale @bogdandrutu

**Comment by pkositsyn** [comment]
@bogdandrutu can we reopen this?

**Comment by pkositsyn** [comment]
@bogdandrutu Can you please take a look?

**Comment by pkositsyn** [comment]
@bogdandrutu @tigrannajaryan @andrewhsu Anyone?

**Comment by jpkrohling** [comment]
Are you able to reopen this one, @pkositsyn?

**Comment by pkositsyn** [comment]
No, I can't

**Pull request closed without merging**
