### PR TITLE
Check for Unmarshallable internal arguments

### PR DESCRIPTION
**Pull request by bogdandrutu**
This has a limitation that do not check for the top level (the result pass to Unmarshal call). The reason is because cannot easily avoid a circular call (can be done by keeping a state in the Map).

Before doing more things, would like to know if this is something we want to support.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

/CC @open-telemetry/collector-approvers

### CODE REVIEW

**Comment by dmitryax** [comment]
What is the goal for this change? Do we want this to automatically detect any configuration parts that are `Unmarshallable` (not only component configs)? Or is there another reason?

**Comment by bogdandrutu** [comment]
> Do we want this to automatically detect any configuration parts (not only component configs) that are Unmarshallable? 

@dmitryax YES :)

**Comment by djaglowski** [comment]
I believe I have found need of this change for migrating `pkg/stanza` unmarshaling to mapstructure/confmap. It appears the PR timed out without any specific objections. Can this be reopened?

**Review by djaglowski — COMMENTED** [review]
This requires a changelog entry and a couple lint fixes, but looks good to me otherwise.

**Comment by djaglowski** [comment]
@bogdandrutu, this just needs a couple minor things. Do you want to update it? Alternatively, mind if I open a new PR with the same + fixes?

**Comment by bogdandrutu** [comment]
@djaglowski go for it, happy to review :)

**Pull request closed without merging**
