### PR TITLE
use gogo proto from jsuereth/protobuf fork for optional support

### PR DESCRIPTION
**Pull request by codeboten**
**Description:**
Draft PR only to capture the work needed to update gogoproto to support optional fields

**Link to tracking Issue:** Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/4258

### CODE REVIEW

**Comment by jsuereth** [comment]
@codeboten Sorry for long delay, just did a round of bug fixes to gogoproto around optional generation for gogofaster.

- Size, Marshal + Unmarshal generation should work w/ optional
- Theoretically this will work with optional *and* setting gogo.nullable=false, but that kind of breaks my head why you'd do this.
- There's a LOT of features in GoGo proto I need to expand test coverage for.   I'll keep churning in the background BUT this should be able to pull in the optional fields we want in OTLP.

**Comment by codeboten** [comment]
@jsuereth thanks for the update, I pulled in the latest changes from the fork into a container I used locally to regenerate the protos in this PR

**Comment by codeboten** [comment]
@jsuereth Thanks for the update, I rebuilt the container using this commit https://github.com/jsuereth/gogoproto/commit/9c8da7e67a62f78c28d3dd4ac3ccca065f0913e4 and regenerated the protos here

**Comment by bogdandrutu** [comment]
@codeboten while discussing with @jsuereth we came with an alternative simpler solution, which is to use custom types for the "optional" fields that implement the "optional" part (since only double values). What do you think?

**Comment by codeboten** [comment]
@bogdandrutu you're thinking we could use the sed script to substitute the optional field with a custom type instead and use that to generated the protos or are you thinking of changing the field to be a custom type instead?

**Comment by jack-berg** [comment]
@bogdandrutu / @jsuereth wondering if you could answer @codeboten's question. If I'm not mistaken the answer dictates whether we need to make changes to the protos or to the collector proto generation code.

**Comment by codeboten** [comment]
@jack-berg the conversation continued on this other [PR](https://github.com/open-telemetry/opentelemetry-collector/pull/4495) (for the 2nd prototype). I'm now working through a third prototype to move away from gogo and use the standard protobuf library + the vtprotobuf extension

**Comment by jack-berg** [comment]
Thanks for the update and for connecting the dots @codeboten! 👍

**Comment by codeboten** [comment]
Closing this for now.

**Pull request closed without merging**
