### PR TITLE
Moved common processor files and updated refs

### LINKED ISSUE #1411: Attribute processor cannot be programmatically configued
**Describe the bug**

Attribute processor cannot be programmatically configured because the `attraction.Settings` is in a private package `"go.opentelemetry.io/collector/internal/processor/attraction"`

It was done in https://github.com/open-telemetry/opentelemetry-collector/pull/1322/files#diff-1ffa1fe6fd27ddd9fe65f23171080144R19 cc) @bogdandrutu 

**Steps to reproduce**

Programmatically configure the attribute processor.

**What did you expect to see?**

Be able to programmatically configure the attribute processor.

**What did you see instead?**

The config object of the attribute processor is composed of structs from private packages.

**What version did you use?**

master/HEAD

**What config did you use?**
Config: (e.g. the yaml config file)

**Environment**
OS: (e.g., "Ubuntu 20.04")
Compiler(if manually compiled): (e.g., "go 14.2")

**Additional context**

### PR DESCRIPTION
**Pull request by joe-elliott**
**Description:** 
- Moved attribute processor config files to the `processor/processorhelper` folder to allow for external use
- Updated references
- Improved code coverage

~There are obviously a lot of ways to expose these files for external use.  I chose the common go convention of using a `pkg` folder, but otherwise kept the folder structure.  I am, however, fine putting these file wherever the maintainers would prefer.  Please let me know if you'd like them in a different location.~
Per discussions below `processor/processorhelper` was agreed upon.

**Link to tracking Issue:**
Fixes #1411

**Testing:**
n/a

**Documentation:**
n/a

### CODE REVIEW

**Comment by joe-elliott** [comment]
There is already a `/processor/processorhelper` package.  Would that make sense?

**Comment by joe-elliott** [comment]
Changes made, but CI is failing.  After investigating I don't believe the failures are related to any of the changes I have made.

**Comment by bogdandrutu** [comment]
Please rebase, the CI for windows-msi was changed

**Comment by bogdandrutu** [comment]
Also please update description :)

**Comment by joe-elliott** [comment]
Thanks for the heads up @bogdandrutu.  Tests passing.

**Pull request merged**
