### PR TITLE
Moving fluentforwardreceiver to contrib repo.

### PR DESCRIPTION
**Pull request by paulosman**
**Description:** 

This is one of two PRs intended to address https://github.com/open-telemetry/opentelemetry-collector/issues/2675. This PR removes fluentforwardreceiver from this repo, the other adds it to the [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib) repo.

Contrib repo PR: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2729

**Link to tracking Issue:**

https://github.com/open-telemetry/opentelemetry-collector/issues/2675

**Testing:**

Confirmed that the project builds locally.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@paulosman the E2E tests [failed](https://github.com/open-telemetry/opentelemetry-collector/pull/2723/checks?check_run_id=2133055027), I think you need to delete TestLog10kDPS/FluentBitToOTLP too.

**Comment by tigrannajaryan** [comment]
Also, please fix the merge conflict.

**Comment by paulosman** [comment]
> @paulosman the E2E tests [failed](https://github.com/open-telemetry/opentelemetry-collector/pull/2723/checks?check_run_id=2133055027), I think you need to delete TestLog10kDPS/FluentBitToOTLP too.

Thanks @tigrannajaryan . I moved the test, now it's failing in the contrib repo, unfortunately. I can try bumping the resourcespec and seeing if that fixes it. 

Also seeing a deb package failure in the build now, but I think that might be transient.

**Comment by tigrannajaryan** [comment]
Please also clean the CI config, remove these bits:
https://github.com/open-telemetry/opentelemetry-collector/blob/4ae0fc11491d5dff0fa54c79ec2bacc3beeeaf62/.github/workflows/build-and-test.yml#L247
https://github.com/open-telemetry/opentelemetry-collector/blob/4ae0fc11491d5dff0fa54c79ec2bacc3beeeaf62/.circleci/config.yml#L94

**Comment by paulosman** [comment]
> Please also clean the CI config, remove these bits:
> https://github.com/open-telemetry/opentelemetry-collector/blob/4ae0fc11491d5dff0fa54c79ec2bacc3beeeaf62/.github/workflows/build-and-test.yml#L247
> 
> 
> https://github.com/open-telemetry/opentelemetry-collector/blob/4ae0fc11491d5dff0fa54c79ec2bacc3beeeaf62/.circleci/config.yml#L94

Thanks, this is done. Looks like there are still two checks failing, (contrib_tests and check-links) but they appear to be failing all builds right now?

**Comment by bogdandrutu** [comment]
Oh now... please rebase

**Comment by paulosman** [comment]
> Oh now... please rebase

Done, now there are new failures :-) Something to do with ports - I can try and debug later today.

**Comment by paulosman** [comment]
> > Oh now... please rebase
> 
> Done, now there are new failures :-) Something to do with ports - I can try and debug later today.

Rebased again and they're passing - think I just got unlucky. @bogdandrutu there's a failure in contrib-tests that looks related to the rename of configmodels => config. Let me know if you want me to try and address that here, otherwise I _think_ this is PR ready to go.

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
