### PR TITLE
Remove configmapprovider.NewInMemory(), not used

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by mx-psi — APPROVED** [review]

**Comment by rmfitzpatrick** [comment]
@bogdandrutu what is the proposed workaround for this usage? https://github.com/signalfx/splunk-otel-collector/blob/889336474101ebbcfeb493bf0d2500b9f4ecd60f/cmd/otelcol/main.go#L383

**Review by codeboten — APPROVED** [review]
@bogdandrutu is the solution to @rmfitzpatrick's question to manage the serialization manually? It looks like there's a TODO around exporting `simpleRetrieved`, would that help in this case?

**Comment by bogdandrutu** [comment]
@rmfitzpatrick @codeboten the solution is here https://github.com/open-telemetry/opentelemetry-collector/pull/4574

**Comment by alolita** [comment]
This removal is also a breaking change for AWS Distro for OpenTelemetry (ADOT) downstream.

**Comment by bogdandrutu** [comment]
@alolita you have the same trick with environment variable config, consider to use the newly added provider that reads from env, see https://github.com/open-telemetry/opentelemetry-collector/pull/4574

**Pull request merged**
