### PR TITLE
Remove deprecated funcs and struct members from featuregate package

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by MovieStoreGuy — APPROVED** [review]

**Comment by MovieStoreGuy** [comment]
Looks like some `go.sum` packages our out of sync.

**Comment by bogdandrutu** [comment]
>  Looks like some go.sum packages our out of sync.

Not sure I understand, the problem here is https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16257

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
I triggered the contrib tests again after merging open-telemetry/opentelemetry-collector-contrib/pull/16257

**Comment by MovieStoreGuy** [comment]
> > Looks like some go.sum packages our out of sync.
> 
> Not sure I understand, the problem here is [open-telemetry/opentelemetry-collector-contrib#16257](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/16257)

I swear I saw a log in the tests saying `missing from go.sum`

**Pull request merged**
