### PR TITLE
Move pdata into an internal package and use aliases in exported package

### PR DESCRIPTION
**Pull request by dmitryax**
This change is the first step towards splitting the pdata package into multiple modules. It implements the approach 3 outlined [here](https://github.com/open-telemetry/opentelemetry-collector/issues/4832).

In this PR, all files from `model/pdata` are moved to `model/internal/pdata` as is, new files with aliases to the internal pdata package are added to the existing `model/pdata` package.

If this is accepted, next it can be easily used to generate other p\<signal\> packages in _addition_ to existing exported pdata package until we find out what to do with components relying on it:
- If we are going to split other components, they can be changed along with switching to the new p\<signal\> packages.
- If we don't split them, we will need to run all the components relying on pdata through the 3-step deprecation process.

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]
This change is necessary to move forward with the plan of splitting the pdata package.

**Review by Aneurysm9 — CHANGES_REQUESTED** [review]
I don't believe that there is yet consensus on https://github.com/open-telemetry/opentelemetry-collector/issues/4832 or agreement that this PR is necessary to effect a split of pdata into multiple modules.  We need to hold off on merging this until a plan for #4832 is agreed.

**Comment by bogdandrutu** [comment]
Timeline of events:
1. Decision to split in multiple packages was made long time, and everyone agreed on.
2. During the implementation of that decision @dmitryax and @bogdandrutu, wrongly made an assumption that the internal package cannot be shared between modules, and will have to expose publicly things that we don't want. That's when the https://github.com/open-telemetry/opentelemetry-collector/issues/4832 was created.
3. During last SIG @Aneurysm9 pointed that the sharing of internal packages is possible, based on go example with the internal/global package. This was documented in the issue.

Now: because of 3) the solution for splitting is trivial (not sure if more documentation is needed). But essentially will have a module with all the "internal not exported" that will be shared by all the other packages that need access to that. This module does not necessary need to be separate module or be inside the `common` module that anyway every other module depends on.

**Comment by dmitryax** [comment]
Looks like we have a consensus [here](https://github.com/open-telemetry/opentelemetry-collector/issues/4832) and [here](https://github.com/open-telemetry/opentelemetry-collector/pull/4918).

@codeboten @Aneurysm9 @tigrannajaryan PTAL at this PR

**Comment by bogdandrutu** [comment]
@open-telemetry/collector-maintainers are we ok to move forward with this intermediate step, since for the final PR there are still "subtle" things to discuss as the final name of the package "trace" vs "ptrace" the final name of the public structs "TracesUnmarshaler" vs "Unmarshaler" which we can focus on a smaller PR that only exposes these.

**Comment by tigrannajaryan** [comment]
> @open-telemetry/collector-maintainers are we ok to move forward with this intermediate step, since for the final PR there are still "subtle" things to discuss as the final name of the package "traces" vs "ptraces" the final name of the public structs "TracesUnmarshaler" vs "Unmarshaler" which we can focus on a smaller PR that only exposes these.

I am OK.

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
