### PR TITLE
[chore] delete unused method on nopHost

### PR DESCRIPTION
**Pull request by atoulme**
#### Description
Delete GetExporters on nopHost as it is no longer part of the interface signature.

This is a no-op and no change in API exposed directly is present since nopHost is not exported.

### CODE REVIEW

**Review by songy23 — APPROVED** [review]

**Comment by songy23** [comment]
Seems contrib tests need updates too

**Review by codeboten — APPROVED** [review]

**Comment by codeboten** [comment]
@atoulme can you confirm that contrib can be updated to not use this method?

**Review by bogdandrutu — APPROVED** [review]
Please make tests pass

**Comment by mx-psi** [comment]
`routingprocessor` needs a fix

**Comment by atoulme** [comment]
https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34899 is open to unblock.

**Pull request merged**
