### PR TITLE
kafkareceiver add otlp_json unmarshaller

### PR DESCRIPTION
**Pull request by tensorchen**
finish #2190

### CODE REVIEW

**Comment by bogdandrutu** [comment]
otlp_json is not yet declared stable.

**Comment by tensorchen** [comment]
@bogdandrutu 
I am concerned that otlpreceiver already has an implementation of otlp_json, so I reused it.

In my actual scenario, the upstream Kafka producer only supports json. In addition, since opentelemetry-proto-gen is an internal package, the external implementation of otlp_json is very cumbersome and low in performance.

**Comment by bogdandrutu** [comment]
@tensorchen what I am trying to say is that, the format has not been frozen, which means breaking changes may occur. If you are ok with that it is fine, but we recommend using the proto format for the moment.

**Comment by tigrannajaryan** [comment]
@tensorchen please add otlp_json to the README and also mention that the format is unstable and breaking changes are possible.

**Pull request closed without merging**
