### PR TITLE
Remove deprecated code from pdata

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Comment by mx-psi** [comment]
Blocked by DataDog/datadog-agent#14067 (and after that, by the bump on contrib)

**Review by codeboten — APPROVED** [review]
Restarted the contrib job

**Comment by bogdandrutu** [comment]
@mx-psi, looks like you miss some:

```
Error: /home/runner/go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/trace@v0.40.0-rc.2.0.20221027084422-34610f5c902d/api/otlp.go:127:20: undefined: ptraceotlp.NewResponse
Error: /home/runner/go/pkg/mod/github.com/!data!dog/datadog-agent/pkg/trace@v0.40.0-rc.2.0.20221027084422-34610f5c902d/api/otlp.go:154:19: undefined: ptraceotlp.NewRequest
FAIL	github.com/open-telemetry/opentelemetry-collector-contrib/internal/components [build failed]
```

**Comment by mx-psi** [comment]
Hopefully I didn't forget anything now, PTAL at open-telemetry/opentelemetry-collector-contrib/pull/15705

**Pull request merged**
