### PR TITLE
Do not expose entire config in the Host API

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jcchavezs** [comment]
@bogdandrutu would you explain the motivation of this change? I see we are narrowing down the interface for this and in general that is good idea but I'd like to understand the reason behind it.

**Comment by bogdandrutu** [comment]
@jcchavezs first of all thanks for reviewing this PR :)

> I see we are narrowing down the interface for this and in general that is good idea but I'd like to understand the reason behind it.

This is the main reason. Second reason is that for the moment we expose the pointer to config and I don't want users to change any config (even with NamedEntity there is a setter), but we probably want to have an immutable object here, something like what I am trying to achieve in https://github.com/open-telemetry/opentelemetry-collector/pull/2576

**Comment by jcchavezs** [comment]
LGTM

**Review by tigrannajaryan — APPROVED** [review]
I believe the only use cases we have need the name so this should be fine.

**Pull request merged**
