### PR TITLE
Update component.Host comments

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jrcamp** [comment]
Discussed in chat. IMO, if we're going to change GetExporters we should change GetExtensions to use the same mechanism.

**Review by pjanotti — APPROVED** [review]

**Review by tigrannajaryan — CHANGES_REQUESTED** [review]
Several contrib components call GetExporters. What's the plan here?

**Comment by bogdandrutu** [comment]
@tigrannajaryan updated to just fix comments for the funcs.

**Review by tigrannajaryan — APPROVED** [review]
LGTM

**Pull request merged**
