### PR TITLE
[configtelemetry] Mark module as stable

### LINKED ISSUE #10277: Stabilize module go.opentelemetry.io/collector/config/configtelemetry
Before stabilizing a module, an approver or maintainer must make sure that the following criteria have been met for at least two successive minor version releases (regardless of when this issue was opened):

- [ ] No open issues or PRs in the module that would require breaking changes
- [x] No TODOs in the module code that would require breaking changes
- [x] No deprecated symbols in the module
- [x] No symbols marked as experimental in the module
- [x] The module follows the [Coding guidelines](https://github.com/open-telemetry/opentelemetry-collector/blob/main/CONTRIBUTING.md)

Please also make sure to publicly announce our intent to stabilize the module on:

- [x] The #otel-collector CNCF Slack Channel
- [x] The #opentelemetry CNCF Slack channel
- [x] A Collector SIG meeting (if unable to attend, just add to the agenda)

To help other people verify the above criteria, please link to the announcement and other links used to complete the above in a comment on this issue.

Once all criteria are met, close this issue by moving this module to the `stable` module set.

### PR DESCRIPTION
**Pull request by mx-psi**
#### Description

Fixes #10277

Depends on #10912

### CODE REVIEW

**Review by atoulme — APPROVED** [review]
Approved after dependency is solved.

**Comment by mx-psi** [comment]
cc @open-telemetry/collector-approvers I believe this is ready to merge!

**Review by TylerHelmuth — APPROVED** [review]

**Review by songy23 — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Personal opinion, I would try first to completely remove this module instead of making it stable. Why?
* Otel doesn't have a concept of telemetry level and us in otel-collector inventing this is not the right thing.
* This concept was added to control "expensive" telemetry (more exactly only metrics), but that can be now controlled with views.

**Comment by mx-psi** [comment]
> This concept was added to control "expensive" telemetry (more exactly only metrics), but that can be now controlled with views.

This feels like a way of how to implement the level (each level corresponds to a set of views), but not an argument to remove the level. We have discussed this explicitly and the conclusion was that views alone would be complex for users to interact with

**Pull request merged**
