### PR TITLE
add gRPC health check

### PR DESCRIPTION
**Pull request by seankhliao**
**Description:** added an option to gRPC server for serving the standard health check service grpc.health.v1.Health

**Link to tracking Issue:** #3040

**Testing:** added test to check that the gRPC service was registered

**Documentation:** added entry in readme for `healthcheck` key

### CODE REVIEW

**Comment by seankhliao** [comment]
I think this should be part of the gRPC server settings rather than an extension to allow load balancers to properly observe if the listener is ready.

**Review by dmitryax — APPROVED** [review]

**Review by codeboten — COMMENTED** [review]
> I think this should be part of the gRPC server settings rather than an extension to allow load balancers to properly observe if the listener is ready.

The change looks good. But I'm curious if the healthcheck extension could be used here instead. With the work to have status reporting per component, the healthcheck extension could be modified to report the health of components and the load balancer could point to that extension's endpoint. Would that address the same use-case?

**Comment by bogdandrutu** [comment]
Also confused about the need to be on the same server with the traffic.

**Comment by bpalermo** [comment]
imho from the load balancer perspective is always better to health check the traffic port directly instead of another that may or may not reflect the state of the underlying service. Specially if we are exposing multiple otel collector ports (e.g. otlp/grpc + otlp/http).

**Comment by gjshao44** [comment]
What is blocking this change? I don't see a way to make AWS ALB health check work without this change

**Comment by gjshao44** [comment]
what is preventing the merge if all checks have passed and changes approved?

**Comment by SurenNihalani** [comment]
How can I help prioritize merge this?

**Comment by gjshao44** [comment]
Suren, i can't setup an AWS ALB for OTEL Collector GRPC endpoint without this feature. If you can merge this, I will greatly appreciate it.We are trying to standardize on OpenTelemetry. I have some other less disirable solutions by bypassing OpenTelemetry, but that will defeat the whole purpose.

**Review by atoulme — APPROVED** [review]

**Comment by gjshao44** [comment]
Suren, I may be confused about the merging process, seems we have two reviewers with write access approved, can the PR be merged now? Can you push the button? Thanks!

**Comment by yurishkuro** [comment]
@codeboten is your concern a blocker?

**Comment by pellepelle3** [comment]
I too really need this, can we get this merged.

**Review by pellepelle3 — APPROVED** [review]

**Comment by pellepelle3** [comment]
> > I think this should be part of the gRPC server settings rather than an extension to allow load balancers to properly observe if the listener is ready.
> 
> The change looks good. But I'm curious if the healthcheck extension could be used here instead. With the work to have status reporting per component, the healthcheck extension could be modified to report the health of components and the load balancer could point to that extension's endpoint. Would that address the same use-case?

The healthcheck extension as is would not work as in aws load balancers require it to be GRPC response not a http, the same as what is being served, the expectation is that should be on the same port as the traffic. You can override the port but even so, it needs to be a GRPC response.

**Comment by atoulme** [comment]
We also implemented receiver specific health checks - see for example splunk_hec, which exposes a health check for specific HEC clients.

**Comment by gjshao44** [comment]
This issue now has 3 reviewers approved, one with a question, not necessarily a blocking one in my opinion. Is that sufficient to get this issue move forward, @SurenNihalani, are you able to merge now? Hope everyone has a good holiday!

**Comment by codeboten** [comment]
> The healthcheck extension as is would not work as in aws load balancers require it to be GRPC response not a http, the same as what is being served, the expectation is that should be on the same port as the traffic. You can override the port but even so, it needs to be a GRPC response.

Thanks for your response @pellepelle3, I missed the notification of your response. To be clear the requirement here is to support a gRPC specific response, regardless of the port this is on correct?

This was discussed at this week's SIG (Dec-20), my opinion was that the best way to implement this would be to support a gRPC response in the healthcheck extension. This would prevent users from having to check multiple ports for each component they have configured of a collector.

Using the healthcheck extension would also provide a single source of truth, as I would find it confusing if the healthcheck extension was to return one status code and individual components could return different ones. If this is acceptable as a solution, then I would suggest adding this as a feature of the healthcheck extension that @mwear has been re-writing (to leverage component status reporting)

One question that @kentquirk brought up in the SIG meeting was whether there was a need for the port to be the same, in the case of the ALB mentioned in this PR, it is definitely possible to [configure alternative ports](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html#health-check-settings) (this is often used to avoid making healthcheck visible externally for services)

**Comment by bpalermo** [comment]
@codeboten I'm not familiar with the health check extension internals, but I wonder how it can reflect the healthiness of multiple receivers.
Let's say I have otlp/grpc (4317) + otlp/http (4318), and one of them becomes unhealthy. I assume the extension will reporting the service as unhealthy and the load balancer will take this endpoint out of serving, although the other port would still be able to server.
Is my understanding correct?

**Comment by codeboten** [comment]
> @codeboten I'm not familiar with the health check extension internals, but I wonder how it can reflect the healthiness of multiple receivers. Let's say I have otlp/grpc (4317) + otlp/http (4318), and one of them becomes unhealthy. I assume the extension will reporting the service as unhealthy and the load balancer will take this endpoint out of serving, although the other port would still be able to server. Is my understanding correct?

That's a great question. I think there should be a mechanism in the healthcheck extension to differentiate between the health of different pipelines. There could also be an aggregate status for the overall health of the collector, but in more specific use-cases, like the one you mention, it would make sense to have a separate path (or port, but i feel like this would get confusing fast) for each pipeline

**Comment by gjshao44** [comment]
@bpalermo, @codeboten, interesting discussion. I am planning to have a different AWS ALB endpoint to serve http and grpc endpoint for an otel collector. The http endpoint is the only one that is working for me currently . Here is a sample configuration annotations that I lifted from our Thanos grpc endpoint for AWS ALB, and I am hoping the otel collector can deliver the same working mechanism:

  default = {
    "kubernetes.io/ingress.class" : "alb",
    "alb.ingress.kubernetes.io/scheme" : "internal",
    "alb.ingress.kubernetes.io/target-type" : "ip",
    "alb.ingress.kubernetes.io/backend-protocol-version" : "GRPC",
    "alb.ingress.kubernetes.io/healthcheck-path" : "/grpc.health.v1.Health.Check",
    "alb.ingress.kubernetes.io/healthcheck-protocol" : "HTTP",
    "alb.ingress.kubernetes.io/success-codes" : "1-99",
    "alb.ingress.kubernetes.io/backend-protocol" : "HTTP",
    "alb.ingress.kubernetes.io/listen-ports" : "[{\"HTTPS\": 443}]",
  }

**Comment by gjshao44** [comment]
@codeboten, follow up on your write-up about the SIG meeting and adding feature to the healthcheck extension, is there an issue tracking the feature?

**Comment by mwear** [comment]
Hi @gjshao44. Here is the tracking issue: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26661. I am actively working on the new version of the healthcheck extension that is based on component status reporting. It has an implementation of the grpc.v1.healthservice: https://github.com/grpc/grpc-proto/blob/master/grpc/health/v1/health.proto as an option. I expect to have a PR up sometime next week.

**Comment by vynu** [comment]
Hello @mwear thanks for working on this ... waiting for your commit .. when can we expect the changes to be part of the release ?

**Comment by mwear** [comment]
I have a PR open for the health check extension here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30673. We will also need some version of https://github.com/open-telemetry/opentelemetry-collector/pull/8684 or https://github.com/open-telemetry/opentelemetry-collector/pull/8788 to provide the extension with status events for exporters. I'll revisit those PRs shortly. I'd appreciate any feedback on any of the PRs I've mentioned.

**Comment by TRAD-Anthony-CKO** [comment]
Any updates on this? I see the PR as closed but multiple people are suffering from this issue.

**Comment by tmegow** [comment]
I am attempting to setup a centralized otel collector which serves via an ALB and gRPC. I find that my target group health checks are failing and it seems this topic might be relevant to my goals. 

May I inquire about the status of this PR/issue?

**Comment by mwear** [comment]
I've written an alternative health check extension that supports both HTTP and gRPC health checks. It's in the process of being reviewed. The full version is here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30673. I am slicing it up into smaller PRs to facilitate review. The current chunk is here: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/33528. Based on this users experience: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30673#issuecomment-2039223996, I think it will work for your use case when the extension becomes available.

**Comment by yurishkuro** [comment]
@mwear why is healthcheck extension a replacement for this PR? Extension will run on a different port, which is very different from what was asked in the original ticket.

**Comment by mwear** [comment]
@yurishkuro the healthcheck extension provides a grpc health server that is based on component status reporting. Component status reporting, while still a work in progress, allows us to derive collector health based on the health of the individual components. As you point out, it does not run on the same port. The need for the health check to be on the same port was debated in this PR and it wasn't clear if it was a hard requirement. I know that a user successfully used the extension on an AWS ALB, which is one of the use cases discussed, see: https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/30673#issuecomment-2039223996.

**Pull request closed without merging**
