### PR TITLE
[pdata] Add Append and EnsureCapacity methods to primitive slices

### PR DESCRIPTION
**Pull request by dmitryax**
Follow-up PR from https://github.com/open-telemetry/opentelemetry-collector/pull/5971:

> No way of increasing the capacity or length. We can discuss about that API.

Given that we have `SetAt` interface not `Append...`, I think it makes sense to have `SetLen`. But I'm open to other suggestions

Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6063

cc @bogdandrutu

### CODE REVIEW

**Comment by bogdandrutu** [comment]
> Given that we have SetAt interface not Append..., I think it makes sense to have SetLen. But I'm open to other suggestions

Confused about why not offering an `Append(vals ...int64)` is not a valid solution as well? 

Some other question:
1. Should we also offer `EnsureCapacity`?

**Comment by dmitryax** [comment]
@bogdandrutu  My reasoning for `SetLan` is coming from the usage. Usually we know length in advance and just set/update existing elements not appending anything. 

Maybe we shouldn't rely on usage and think of the slices in more abstracted way. In that case `Append` and `EnsureCapacity` probably is better, since it provides more flexibility going forward

**Comment by bogdandrutu** [comment]
I think an `Append` and `EnsureCapacity` make total sense and moves this so be similar with other slices. In addition we can also have `SetLen` but want tot understand if it does allocation if not enough space or crash (for example reslicing a slice crash if not enough capacity). I think `SetLen` can wait until we see more use-cases, what do you think?

**Comment by dmitryax** [comment]
> I think SetLen can wait until we see more use-cases, what do you think?

Ok sounds good. let's do that

**Comment by dmitryax** [comment]
@bogdandrutu , updated

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Need a rebase

**Comment by dmitryax** [comment]
Rebased

**Pull request merged**
