### PR TITLE
Add graph-based implemenation of HandleZPages

### PR DESCRIPTION
**Pull request by djaglowski**
Follows #7108

### CODE REVIEW

**Comment by djaglowski** [comment]
Since this would complete the graph-based implementation of the `service.pipelines` interface, I am temporarily updating the associated feature gate to beta, which will run all tests with this implementation enabled by default. I will leave the PR in draft state until this is reverted.

**Comment by djaglowski** [comment]
Test coverage for these changes relies on changes in #7110.

**Comment by djaglowski** [comment]
I've overhauled this PR and believe it's a cleaner solution now.

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Merging since we want this in the next release.

**Pull request merged**
