### PR TITLE
Fix typo in examples/k8s/otel-config.yaml

### PR DESCRIPTION
**Pull request by johnkerl**
**Description:** Change `endpoing` to `endpoint` in `examples/k8s/otel-config.yaml`

### CODE REVIEW

**Comment by johnkerl** [comment]
(Looking into the CLA ...)

**Review by carlosalberto — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Comment by johnkerl** [comment]
Sorry for the delay! Getting the CLA through legal. If it gets auto-closed I'll resubmit.

Thanks!

**Comment by johnkerl** [comment]
@carlosalberto @bogdandrutu the CLA is now signed -- can you merge now? Please let me know if I need another step ..

**Comment by johnkerl** [comment]
Thanks!! :)

**Pull request merged**
