### PR TITLE
Synchronize docs changes between website and main repo

### PR DESCRIPTION
**Pull request by austinlparker**
There were some docs changes to the website copy that were lost between when we opened the initial PR moving docs here and when those changes were merged and published to the website; This PR restores those changes.

### CODE REVIEW

**Review by carlosalberto — APPROVED** [review]

**Comment by austinlparker** [comment]
Once this PR is merged, you would need to re-run the workflow.

**Comment by bogdandrutu** [comment]
@austinlparker please rebase the PR, failing task is fixed on head

**Comment by tigrannajaryan** [comment]
I see changes that seem unrelated. Rebase gone wrong perhaps?

**Comment by austinlparker** [comment]
yeah, i'm gonna re-do the PR, one minute

**Pull request closed without merging**
