### PR TITLE
make sure ci job uses always the latest go patch available

### PR DESCRIPTION
**Pull request by cpanato**
**Description:** 

- make sure ci job uses always the latest go patch available
- update deprecated goreleaser flag

### CODE REVIEW

**Comment by cpanato** [comment]
cc @jpkrohling

**Comment by TylerHelmuth** [comment]
If I recall correctly I purposefully switch from using the latest patch version to specifying a specific patch version so that we had complete control over the go version we built/tested with

**Comment by cpanato** [comment]
> purposefully switch from using the latest patch version to spe

I see, but then should we pin that to the patch version and not use the `~`?

**Comment by cpanato** [comment]
@jpkrohling @TylerHelmuth is this something you guys want to have? if yes can you reopen and lets merge it?

**Comment by cpanato** [comment]
i will rebase and fix the conflicts

**Comment by TylerHelmuth** [comment]
Agreed

**Comment by cpanato** [comment]
@jpkrohling @TylerHelmuth done, ptal

thanks!

**Comment by jpkrohling** [comment]
I asked the Collector leads if it's something we want, and if so, I'll fix the conflicts.

**Comment by cpanato** [comment]
rebased

**Comment by codeboten** [comment]
I don't see why we shouldn't do this, although one thing to keep in mind is that CI will be broken when a new version of go is released (because of the helpful toolchain directive)

**Comment by jpkrohling** [comment]
Can't renovate take care of bumping it as well?

**Comment by cpanato** [comment]
renovate or dependabot can bump

**Comment by mx-psi** [comment]
> renovate or dependabot can bump

Is this something we have an issue/PR for?

**Pull request closed without merging**
