### PR TITLE
[exporterhelper] alternative tracing of components

### PR DESCRIPTION
**Pull request by codeboten**
Instead of providing an interface that is then implemented by each helper, this proposes using the existing components as is and wrapping Consume<Signal>Func in each helper. This reduces new APIs, but it does mean that the wrapping code will need to be implemented inside each helper.

Alternative to https://github.com/open-telemetry/opentelemetry-collector/pull/8833

Part of https://github.com/open-telemetry/opentelemetry-collector/issues/8804

### CODE REVIEW

**Comment by TylerHelmuth** [comment]
@codeboten with this solution, any component that is not using the helper would have to manually instrument themselves to show up in the trace correct?

**Comment by codeboten** [comment]
@TylerHelmuth correct

**Comment by dmitryax** [comment]
The persistent queue drops the context, so this will break tracing if persistent queue is enabled

**Comment by codeboten** [comment]
@bogdandrutu @TylerHelmuth @dmitryax @djaglowski is there a preference between this and #8833? This one has less surface API, but I guess it does mean that anyone who isn't using helpers would have to implement this call themselves.

**Comment by TylerHelmuth** [comment]
@codeboten the helpers are pretty ubiquitous right?  All the components in Core and Contrib would be instrumented?

**Comment by dmitryax** [comment]
@codeboten, unfortunately, neither of them will work with the enabled persistent queue. I think we need to keep it after the queue until we find a way to propagate the context through the persistent queue if we want to. But it may introduce a significant overhead.

**Pull request closed without merging**
