### PR TITLE
[telemetry] mark useOtelForInternalMetrics stable

### PR DESCRIPTION
**Pull request by codeboten**
This marks the flag as stable. Leaving this as a draft until v0.92.0 is released.

Closes https://github.com/open-telemetry/opentelemetry-collector/issues/8962
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/816

### CODE REVIEW

**Review by TylerHelmuth — COMMENTED** [review]
It's beautiful.  What impact does this have on components in Contrib, like [tailsamplingprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/tailsamplingprocessor/metrics.go) or [filterprocessor](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/telemetry.go), that use OC?

**Review by mwear — APPROVED** [review]

**Comment by atoulme** [comment]
Same question as Tyler regarding the Splunk HEC exporter: https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/splunkhecexporter/heartbeat.go#L58

**Comment by codeboten** [comment]
Should have no impact, the opencensus bridge is still in place to receive OC metrics

**Review by TylerHelmuth — APPROVED** [review]

**Comment by codeboten** [comment]
@TylerHelmuth @atoulme the global OC registry is still usable by components: https://github.com/open-telemetry/opentelemetry-collector/blob/49e14a1480a180acd05d8139d1752b1943b2a92e/service/telemetry.go#L137

**Review by atoulme — APPROVED** [review]

**Comment by splunkericl** [comment]
Can this PR wait for a couple releases? Our team relies on OpenCensus reporting and the metrics generated. Some metrics in queue_sender like queue size and queue capacity are important for our business.

We only notice the OpenCensus metrics is being removed because of the feature gate change in V0.92. I can imagine there are other users in the same boat. Would it make sense to wait for a couple releases so users have time to migrate off OpenCensus metrics?

**Comment by codeboten** [comment]
>  Some metrics in queue_sender like queue size and queue capacity are important for our business.

Thanks for the feedback @splunkericl! Can you specify which metrics? Queue size and capacity were added to the opentelemetry generated metrics some time ago. See https://github.com/open-telemetry/opentelemetry-collector/pull/8716

**Review by mx-psi — APPROVED** [review]

**Comment by codeboten** [comment]
> Our team relies on OpenCensus reporting and the metrics generated

@splunkericl just more follow up on this, any components that's using OpenCensus to generate metrics can continue to do so even with this change. The telemetry configuration for the Collector still supports the OpenCensus bridge.

**Comment by splunkericl** [comment]
@codeboten ah I see. So the application generating open census metrics will see them in the prometheus server spawned? If that is the case that should be fine.

Our application has been scraping against the prometheus metrics endpoint and use these metrics for business logics. As long as the workflow is still the same it should be fine and gives us more time to migrate to start using OTEL metrics framework.

**Comment by codeboten** [comment]
@splunkericl right. The metrics that are being exposed via prometheus today will continue to be exposed in the same manner, regardless of how those metrics are being recorded inside the collector itself. 

You can see a sample output of the metrics before and after the flag is used here: https://github.com/open-telemetry/opentelemetry-collector/pull/9029#issue-2021348799

Any component (in core or in contrib) that is still recording its metrics via opencensus will continue to see its metrics exported via the collector's internal prometheus endpoint. Note there is an open issue to migrate components away in the future though: https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/29867. This would allow us to remove a dependency on the opencensus library.

**Comment by splunkericl** [comment]
Got it. Thanks for the explanations!

**Pull request merged**
