### PR TITLE
[chore] otlpreceiver: README: markdown formatting fix

### PR DESCRIPTION
**Pull request by dubek**
#### Description

Small formatting fix (add missing backquote) in README of otlpreceiver.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please sign the CLA. I know is just a small comment, but these are the rules.

**Review by codeboten — COMMENTED** [review]
Thanks @dubek!

**Comment by dubek** [comment]
I signed the CLA and rebased the branch.

**Comment by dubek** [comment]
Added `[chore]` to PR title to skip changelog workflow in Github Actions.

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
