### PR TITLE
Add zstd decompression support to HTTPServerSettings

### PR DESCRIPTION
**Pull request by tigrannajaryan**
This adds ability to decompress zstd-compressed HTTP requests to all receivers that use HTTPServerSettings.

Also added missing error handling for the case when an unsupported compression type was used in the request. Now it correctly returns 400 Bad Request. Also added a unit test to verify this case.

Once this is merged I will submit a PR in contrib repo to add end-to-end tests that use zstd compression in the testbed.

### CODE REVIEW

**Review by atoulme — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
> Change looks good. Please add a second changelog entry file for the bugfix

Done.

**Comment by bogdandrutu** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-collector/pull/7636?

**Comment by bogdandrutu** [comment]
Please look at the other PR and incorporate that change as well.

**Comment by tigrannajaryan** [comment]
I looked at https://github.com/open-telemetry/opentelemetry-collector/pull/7636 and it seems to do 2 additional things:
1. Adds snapy decompression. I think this can be added in a separate PR.
1. It closes the request Body after handling the request, which is not necessary (Go docs only [require it for clients, not for servers](https://pkg.go.dev/net/http#Request), which is where the confusion probably comes from). However reading the code helped me discover that I did not close zstd Decoder correctly. Fixed now in [this commit](https://github.com/open-telemetry/opentelemetry-collector/pull/7927/commits/2ac04a0ddb46b40382a861624639959500eaf09d), so the PR was useful! :-)

**Review by codeboten — APPROVED** [review]
Thanks for addressing my comments @tigrannajaryan

**Pull request merged**
