### PR TITLE
Run windows tests only on github action

### PR DESCRIPTION
**Pull request by bogdandrutu**
Updates https://github.com/open-telemetry/opentelemetry-collector/issues/1234

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Please add a commit message/PR description to explain the motivation of the change.

**Comment by bogdandrutu** [comment]
Part of the https://github.com/open-telemetry/opentelemetry-collector/issues/1234, added a comment that updates this issue.

**Comment by tigrannajaryan** [comment]
So, we are removing windows tests from CircleCI but keep the rest. Is there something special about windows tests? I still don't quite understand why this change.

**Comment by bogdandrutu** [comment]
>So, we are removing windows tests from CircleCI but keep the rest. Is there something special about windows tests? I still don't quite understand why this change. 

I want to do an incremental move, start task by task until we completely move away from circleCI.

**Review by tigrannajaryan — APPROVED** [review]

**Pull request merged**
