### PR TITLE
Replace viper with koanf in builder

### PR DESCRIPTION
**Pull request by rleungx**
**Description:**
Just as the title says and also clean up the dependencies.

**Link to tracking Issue:** #4732 

**Testing:** < Describe what testing was performed and which tests were added.>
Not sure if needed

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]
@jpkrohling are you ok with this change?

**Review by jpkrohling — APPROVED** [review]
Apparently, there's no change in the user-visible behavior. I'm fine with this change.

**Comment by jpkrohling** [comment]
The tests seem to be failing, I just sent in a PR fixing them: https://github.com/open-telemetry/opentelemetry-collector/pull/4771

**Comment by jpkrohling** [comment]
PR rebased

**Comment by jpkrohling** [comment]
There's something wrong: running `make otelcorecol` yields changes to the generates sources, which isn't expected. Here's the diff:

```go
diff --git a/cmd/otelcorecol/main.go b/cmd/otelcorecol/main.go
index 8f4124d6..b0885d17 100644
--- a/cmd/otelcorecol/main.go
+++ b/cmd/otelcorecol/main.go
@@ -19,9 +19,9 @@ func main() {
        }
 
        info := component.BuildInfo{
-               Command:     "otelcorecol",
-               Description: "Local OpenTelemetry Collector binary, testing only.",
-               Version:     "0.43.1-dev",
+               Command:     "otelcol-custom",
+               Description: "Custom OpenTelemetry Collector distribution",
+               Version:     "1.0.0",
        }
 
        if err := run(service.CollectorSettings{BuildInfo: info, Factories: factories}); err != nil {
```

**Review by jpkrohling — CHANGES_REQUESTED** [review]
I'm blocking this, as the generated resources seem to have been affected when they shouldn't.

**Comment by jpkrohling** [comment]
@rleungx, are you still interested in this one?

**Review by bogdandrutu — APPROVED** [review]

**Comment by rleungx** [comment]
> There's something wrong: running `make otelcorecol` yields changes to the generates sources, which isn't expected. Here's the diff:
> 
> ```go
> diff --git a/cmd/otelcorecol/main.go b/cmd/otelcorecol/main.go
> index 8f4124d6..b0885d17 100644
> --- a/cmd/otelcorecol/main.go
> +++ b/cmd/otelcorecol/main.go
> @@ -19,9 +19,9 @@ func main() {
>         }
>  
>         info := component.BuildInfo{
> -               Command:     "otelcorecol",
> -               Description: "Local OpenTelemetry Collector binary, testing only.",
> -               Version:     "0.43.1-dev",
> +               Command:     "otelcol-custom",
> +               Description: "Custom OpenTelemetry Collector distribution",
> +               Version:     "1.0.0",
>         }
>  
>         if err := run(service.CollectorSettings{BuildInfo: info, Factories: factories}); err != nil {
> ```

Fixed, PTAL.

**Review by bogdandrutu — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Please resolve the conflicts, the change looks good otherwise

**Pull request merged**
