### PR TITLE
Fix support for new line in config URI location (#6310)

### PR DESCRIPTION
**Pull request by codeboten**
Merging change from release branch

Signed-off-by: Bogdan <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by Aneurysm9 — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Don't merge this until I also tag/prepare that

**Comment by bogdandrutu** [comment]
Not sure how you want to resolve the conflicts ... since that may change the commit hash ...

**Comment by bogdandrutu** [comment]
I can resolve the conflicts in the UI? Is that what you cannot do?

**Comment by bogdandrutu** [comment]
I think we need an intermediate branch. because the UI will merge the fix commit to `release/v0.62.x`. So we can go from `release/v0.62.x` to `release/v0.62.x.temp` and merge from there so I don't mess with `release/v0.62.x`

**Comment by codeboten** [comment]
i can't merge in the ui or push to the protected branch using `git`

**Comment by bogdandrutu** [comment]
>  i can't merge in the ui or push to the protected branch using git

Let's debug that maybe tomorrow in a zoom call. For the moment, can you create the same PR but from `release/v0.62.x.temp`, so I can use the UI to do the resolve?

**Comment by codeboten** [comment]
@bogdandrutu https://github.com/open-telemetry/opentelemetry-collector/pull/6313

**Pull request closed without merging**
