### PR TITLE
Clarify that Watchable is not used for continuous watching

### PR DESCRIPTION
**Pull request by rakyll**
Watching is a loaded term and gives an impression that it's a mechanism that could be used to continuously report new configuration changes. We could have called this interface a Waiter, but it's too late to make changes, hence adding some comments to clarify it's not used for continuous config updates.

### CODE REVIEW

**Review by jrcamp — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@pjanotti PTAL.

**Comment by tigrannajaryan** [comment]
Lint errors:
```
service/parserprovider/provider.go:34:47: `recieved` is a misspelling of `received` (misspell)
	// It blocks until configuration updates are recieved and can
	                                             ^
service/parserprovider/provider.go:37:13: `continously` is a misspelling of `continuously` (misspell)
	// changes continously.
	           ^
make[2]: *** [Makefile.Common:26: lint] Error 1
```

**Review by pjanotti — APPROVED** [review]
LGTM (- minor typo)

I like the rename idea: the interface to `Waiter` and perhaps the method to `WaitForUpdate` makes the purpose/usage clear.

**Comment by tigrannajaryan** [comment]
CodeQL is unhappy about something, but I have no idea what it wants.

**Comment by tigrannajaryan** [comment]
> CodeQL is unhappy about something, but I have no idea what it wants.

@rakyll please make sure the build passes.

**Review by bogdandrutu — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
