### PR TITLE
chore(readme): otlphttp endpoint

### PR DESCRIPTION
**Pull request by sylwit**
**Documentation:** 

endpoint shouldn't contain the path

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
@sylwit please sign the CLA to get this change merged. Thanks!

**Comment by sylwit** [comment]
Hi @codeboten 

I already signed the CLA. Just re did it now but it's not detected.

Screenshot 2023-01-10 at 2 28 28 PM

**Comment by codeboten** [comment]
Thanks for the quick followup @sylwit!

**Pull request merged**
