### PR TITLE
[chore] Prepare release v1.1.0/v0.91.0

### PR DESCRIPTION
**Pull request by opentelemetrybot**
The following commands were run to prepare this release:
- make chlog-update VERSION=v1.1.0/v0.91.0
- make prepare-release PREVIOUS_VERSION=1.0.0 RELEASE_CANDIDATE=1.1.0 MODSET=stable
- make prepare-release PREVIOUS_VERSION=0.90.1 RELEASE_CANDIDATE=0.91.0 MODSET=beta

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
Should there be a 1.1.0 release?

**Comment by codeboten** [comment]
Oh I see this change https://github.com/open-telemetry/opentelemetry-collector/pull/9038, i couldn't see a changelog for it which is how i missed it :D

**Comment by dmitryax** [comment]
> Oh I see this change https://github.com/open-telemetry/opentelemetry-collector/pull/9038, i couldn't see a changelog for it which is how i missed it :D

@codeboten, maybe we can just ignore it and skip the stable module set release this time? I can relax the tooling requirements

**Comment by codeboten** [comment]
@dmitryax either that or add a "improved documentation" changelog entry 😄

**Comment by dmitryax** [comment]
Given that I addressed only one part of it, I don't think it's a significant enough change to warrant a new release version. I submitted [another issue](https://github.com/open-telemetry/opentelemetry-collector/issues/9070) to address other parts. Will update the tooling as well

**Pull request closed without merging**
