### PR TITLE
Use int64 for cgroup v1 parsing

### PR DESCRIPTION
**Pull request by perher**
**Description:**
Use int64 when parsing memory limits for cgroup V1 code (V2 code already does this)

**Link to tracking Issue:**
https://github.com/open-telemetry/opentelemetry-collector/issues/6443

**Testing:**
Tested on Linux 32-bit build on Ubuntu 22.04 with cgroup v1 enabled

### CODE REVIEW

**Review by dmitryax — COMMENTED** [review]
Thanks for the contribution. Please add a changelog entry file

**Comment by perher** [comment]
Added changelog entry

**Review by dmitryax — APPROVED** [review]

**Comment by bogdandrutu** [comment]
/cc @dashpole 

I think this code was copied/imported from somewhere, want to make sure we don't diverge too much from there.

**Comment by dashpole** [comment]
I think it comes from here: https://github.com/uber-go/automaxprocs/blob/master/internal/cgroups/cgroup.go#L73.  I'm not personally worried about diverging, but it may be good to try and upstream this fix, as I assume it would impact their users as well.

**Review by dashpole — APPROVED** [review]

**Pull request merged**
