### PR TITLE
Replace usage of path.Join with filepath.Join, better windows support

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
Were these leftover from https://github.com/open-telemetry/opentelemetry-collector/issues/4633?

**Review by codeboten — COMMENTED** [review]
Appears this made windows tests mad :D

**Comment by bogdandrutu** [comment]
@codeboten maybe, that issue was all about `path.Join(".",` but it is hard to do only in a specific case. For consistency and easy to follow rule, I want to use "filepath" everywhere.

**Comment by bogdandrutu** [comment]
> Appears this made windows tests mad :D

This is because in 2 cases we had to use "path" package, when we are constructing URL path :))

**Pull request merged**
