### PR TITLE
configHttp: Ability to pass telemetry settings to http instrument library that instruments the otlphttp exporter

### PR DESCRIPTION
**Pull request by Sprakhar97**
**Description:**
1. Made changes to pass telemetry settings to configHttp Toclient to configure the instrumentation library
2. Instrumented the otlphttp exporter using otel instrumentation library to enable observability.
**Link to tracking Issue:** 
Fixes: #4449

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Not sure what happened (looks like a merge of 2 PRs), but you need to sign the CLA.

**Comment by Sprakhar97** [comment]
@bogdandrutu can you please approve the workflows for this PR

**Review by bogdandrutu — APPROVED** [review]

**Comment by Sprakhar97** [comment]
@bogdandrutu, @ any guidelines on how to merge changes made to libraries on which contrib repo/tests have dependency?

**Comment by bogdandrutu** [comment]
@Sprakhar97 not sure what you ask for, but after this change is merged, you need to "make update-otel" in contrib, then fix all the problems :D

**Comment by Sprakhar97** [comment]
@bogdandrutu I thought merge was blocked due to failing otel-collector-contrib test but now I realised I didn't have merge rights :D

**Pull request merged**
