### PR TITLE
Paging metric -- add device label

### PR DESCRIPTION
**Pull request by tbarker25**
**Description:**
Extend paging scraper to collect per-device paging stats on Linux -- this will match the behavior for Windows. See tracking issue for more details.

**Link to tracking Issue:**  #3447

**Testing:** Unit tests extended for this case.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@dmitryax please review and let me know if we need any changes fr signalfx

**Comment by punya** [comment]
Would it be worth adding a unit test that scrapes a fixed, known `/proc/swaps` file?

**Comment by tigrannajaryan** [comment]
The build failed. Make sure `make` passes.

**Comment by tbarker25** [comment]
> Would it be worth adding a unit test that scrapes a fixed, known `/proc/swaps` file?

Good idea. Done 😄

**Comment by bogdandrutu** [comment]
Please rebase

**Comment by tbarker25** [comment]
> Please rebase

Done

**Comment by bogdandrutu** [comment]
@tbarker25 sorry, unfortunately this needs to be moved to contrib, since we moved the hostmetricsreceiver there.

**Comment by tbarker25** [comment]
Moved to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4854

**Pull request closed without merging**
