### PR TITLE
Deprecate consumerprofiles module in favor of xconsumer

### PR DESCRIPTION
**Pull request by dmitryax**
To allow adding more experimental data types. First step towards https://github.com/open-telemetry/opentelemetry-collector/issues/11778

### CODE REVIEW

**Review by mx-psi — COMMENTED** [review]
This looks good to me, but given other PRs like #11769 and that we have had this discussion before, should we first open a small PR on the coding guidelines stating what naming convention we use?

I personally like an `exp` suffix

**Review by bogdandrutu — APPROVED** [review]

**Comment by dmitryax** [comment]
Waiting for [the vote](https://github.com/open-telemetry/opentelemetry-collector/issues/11783) results before merging

**Comment by dmitryax** [comment]
Updated PR according to the latest guidelines https://github.com/open-telemetry/opentelemetry-collector/pull/11836

**Review by dmathieu — APPROVED** [review]

**Review by mx-psi — APPROVED** [review]

**Comment by mx-psi** [comment]
We are blocked here because of #11840 :/ I am not sure how to solve it, maybe we need to revert #11766 for now

**Pull request merged**
