### PR TITLE
[chore] Merge release/v0.102.x into main replacement

### PR DESCRIPTION
**Pull request by mx-psi**
Replacement of #10327 following step 4:

> If you see merge conflicts when creating the pull request, do the following:
Create a new branch from origin:main.
Merge the release/<release-series> branch into the new branch.
Resolve the conflicts.
Create another pull request to the main branch from the new branch to replace the pull request from the release/<release-series> branch.

### CODE REVIEW

**Review by djaglowski — APPROVED** [review]

**Review by evan-bradley — APPROVED** [review]
Not sure I understand why there are no changes, but based on the commits this looks good to me.

It does seem like it's [missing the 0.102.1 release](https://github.com/mx-psi/opentelemetry-collector/blob/mx-psi/release/v0.102.x-fix-merge-conflicts/cmd/builder/internal/builder/config.go#L20), but I think that can be done in a follow-up.

**Review by songy23 — APPROVED** [review]

**Comment by mx-psi** [comment]
> Not sure I understand why there are no changes, but based on the commits this looks good to me.

This is to get the same commit SHA on main as we have on the `release/v0.102.x`. The contents of all the commits are already on main, so the actual diff is nil.

> It does seem like it's [missing the 0.102.1 release](https://github.com/mx-psi/opentelemetry-collector/blob/mx-psi/release/v0.102.x-fix-merge-conflicts/cmd/builder/internal/builder/config.go?rgh-link-date=2024-06-05T14%3A19%3A52Z#L20), but I think that can be done in a follow-up.

This may actually be important I think :/ let me double check

**Comment by mx-psi** [comment]
(Please don't merge this yet even if you have permissions, I am checking the builder thing)

**Comment by mx-psi** [comment]
Replaced by #10329, it was missing 7218b4cd1d66a627a44f5b19f8e2046a291e7826 indeed

**Pull request closed without merging**
