### PR TITLE
Small nits in otlptext

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by jrcamp** [comment]
Not going to keep it in a separate package under otlp? ie `otlp/json`, `otlp/text` etc.

**Comment by tigrannajaryan** [comment]
Needs rebase.

**Comment by bogdandrutu** [comment]
@tigrannajaryan PTAL

**Comment by bogdandrutu** [comment]
@jrcamp we can discuss the move in other package or not later, but these changes are still useful :)

**Review by jrcamp — APPROVED** [review]

**Pull request merged**
