### PR TITLE
[consumer] Add tracing to all the components

### LINKED ISSUE #8804: Add tracing information to all components
Now that it is possible to emit traces from the Collector, it would be great produce spans consistently across components. This issue is a general issue that will include a checklist for all components in this repo.

**Describe the solution you'd like**
Each component produces a span using the `StartTracesOp` and `EndTracesOp` methods available in obsreport.

### PR DESCRIPTION
**Pull request by iblancasa**
#### Description
Add tracing to all the components

#### Link to tracking issue
Fixes #8804

#### Testing

Based on https://github.com/open-telemetry/opentelemetry-collector/pull/8833

### CODE REVIEW

**Review by codeboten — COMMENTED** [review]
This has the same downsides of the original PR which is that it exposes additional interface for the consumer package. I suggested https://github.com/open-telemetry/opentelemetry-collector/pull/8910 as an alternative implementation but there were some challenges with that one as well.

Pinging @dmitryax and @bogdandrutu as they reviewed the original PRs

**Comment by iblancasa** [comment]
> This has the same downsides of the original PR which is that it exposes additional interface for the consumer package. I suggested #8910 as an alternative implementation but there were some challenges with that one as well.
> 
> Pinging @dmitryax and @bogdandrutu as they reviewed the original PRs

Sorry. Didn't see that one.

I would happily retake the other approach if preferred or research any possible improvements.

**Review by djaglowski — COMMENTED** [review]
It may be outside the scope of this PR but it would be nice if, as we are adding telemetry to components, we could make sure we're using the attributes described on https://github.com/open-telemetry/opentelemetry-collector/issues/11179.

**Comment by iblancasa** [comment]
Closing singe more discussion is needed.

**Pull request closed without merging**
