### PR TITLE
Update Kubernetes example to latest version

### PR DESCRIPTION
**Pull request by shree007**
**Description:** 
The k8s example [here](https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector/main/examples/k8s/otel-config.yaml) has old otel collector image which does not had the new tls config implementation so replacing with new one and command line flag --mem-ballast-size-mib has been deprecated so removed that flag as well.

**Link to tracking Issue:** 
[4247](https://github.com/open-telemetry/opentelemetry-collector/issues/4247)

**Testing:** 
I performed following steps in minikube k8s
$ kubectl apply  -f otel-config.yaml
$ kubectl get pod

and checked all pod were up and there were no TLS error

**Documentation:** 
Once it gets merged I will update the docs.

### CODE REVIEW

**Comment by jpkrohling** [comment]
Closing and opening the PR to see if EasyCLA gets triggered.

**Comment by codeboten** [comment]
Superseeded by https://github.com/open-telemetry/opentelemetry-collector/pull/4329

**Pull request closed without merging**
