### PR TITLE
Start enforcing grpc server implementation to embed UnimplementedGRPCServer, dissallow client implementation

### PR DESCRIPTION
**Pull request by bogdandrutu**
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6966

This pattern is inspired by the gRPC generated code.

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Review by dmitryax — APPROVED** [review]
LGTM

**Comment by dmitryax** [comment]
cc @mx-psi . It looks like datadog-agent needs to update its GRPCServer implementation to include `UnimplementedGRPCServer`

**Comment by bogdandrutu** [comment]
@dmitryax @mx-psi probably in this PR I should not add yet the "unexported" func in the interface, and add it in the next version? This way we give DD and others a chance to fix that?

**Comment by dmitryax** [comment]
> probably in this PR I should not add yet the "unexported" func in the interface, and add it in the next version? This way we give DD and others a chance to fix that?

Sounds like a good plan.

**Comment by bogdandrutu** [comment]
Later add:

```golang
	// unexported disallow implementation of the GRPCClient.
	unexported()
```

**Comment by mx-psi** [comment]
> /cc @mx-psi please start embedding the "Unimplemented" struct :)

ACK, will do

**Pull request merged**
