### PR TITLE
receiver/prometheus: roundtrip Prometheus->Pdata direct conversion without OpenCensus

### LINKED ISSUE #3691: receiver/prometheus/internal: use actual startTimeMs of interval for toDoubleValue
Coming here from a report by @bogdandrutu in https://github.com/open-telemetry/opentelemetry-collector/pull/3674#pullrequestreview-712052673 which is a translation of this code https://github.com/open-telemetry/opentelemetry-collector/blob/6cce4224c6e7e8480c4dd279c18943bfcd399646/receiver/prometheusreceiver/internal/metricfamily.go#L387-L392
which doesn't follow the actual convention for cumulative types requested by the OTEL data definitions https://github.com/open-telemetry/opentelemetry-proto/blob/bc8ee79d8e01faf3310af2987268e94285f354da/opentelemetry/proto/metrics/v1/metrics.proto#L132-L140
which says 
Screen Shot 2021-07-21 at 4 25 51 PM

The actual fix for this will involve deriving the startTimestamp from the transaction itself and passing that into newMetric* functions and then when we have a cumulative type, we shall then use it.

I am filing this issue so that when the bug fix is made, we can propagate it and then have proper parity tests instead of firstly fixing it in an unrelated pull request. /cc @cuonglm to spectate. @bogdandrutu @alolita please assign this issue to me.

### PR DESCRIPTION
**Pull request by odeke-em**
Wire up and use the direct Prometheus->Pdata conversion end to end.
With this change the receiver will no longer need OpenCensus.

This change will involve more follow-ups that just migrate over the tests,
because we don't want a super bloated/massive PR.
    
Fixes #3691
Depends on PR #3694
Depends on PR #3695

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Please rebase and fix conflicts.

**Comment by bogdandrutu** [comment]
```
ok  	go.opentelemetry.io/collector/receiver/otlpreceiver/internal/trace	0.058s
panic: interface conversion: v1.isMetric_Data is *v1.Metric_Sum, not *v1.Metric_Summary

goroutine 156 [running]:
go.opentelemetry.io/collector/model/pdata.Metric.Summary(...)
	D:/a/opentelemetry-collector/opentelemetry-collector/model/pdata/metrics.go:207
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.adjustStartTimestampPdata(0x40790ccccccccccd, 0xc000929708)
	D:/a/opentelemetry-collector/opentelemetry-collector/receiver/prometheusreceiver/internal/otlp_transaction.go:206 +0x1f0
go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*transactionPdata).Commit(0xc0006328c0, 0x66fecc, 0xed89d97fb)
	D:/a/opentelemetry-collector/opentelemetry-collector/receiver/prometheusreceiver/internal/otlp_transaction.go:178 +0x1c5
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1(0xc00001dce8, 0xc00001dcf8, 0xc00077f440)
	C:/Users/runneradmin/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210621150501-ff58416a0b02/scrape/scrape.go:1195 +0x50
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc00077f440, 0x3b9aca00, 0x3b9aca00, 0x0, 0x0, 0x0, 0x66fecc, 0xed89d97fb, 0x400bca0, 0x0, ...)
	C:/Users/runneradmin/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210621150501-ff58416a0b02/scrape/scrape.go:1262 +0xb58
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc00077f440, 0x3b9aca00, 0x3b9aca00, 0x0)
	C:/Users/runneradmin/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210621150501-ff58416a0b02/scrape/scrape.go:1148 +0x37e
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	C:/Users/runneradmin/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210621150501-ff58416a0b02/scrape/scrape.go:564 +0xa0e
```

**Comment by odeke-em** [comment]
> ```
> 
> ok  	go.opentelemetry.io/collector/receiver/otlpreceiver/internal/trace	0.058s
> 
> panic: interface conversion: v1.isMetric_Data is *v1.Metric_Sum, not *v1.Metric_Summary
> 
> 
> 
> goroutine 156 [running]:
> 
> go.opentelemetry.io/collector/model/pdata.Metric.Summary(...)
> 
> 	D:/a/opentelemetry-collector/opentelemetry-collector/model/pdata/metrics.go:207
> 
> go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.adjustStartTimestampPdata(0x40790ccccccccccd, 0xc000929708)
> 
> 	D:/a/opentelemetry-collector/opentelemetry-collector/receiver/prometheusreceiver/internal/otlp_transaction.go:206 +0x1f0
> 
> go.opentelemetry.io/collector/receiver/prometheusreceiver/internal.(*transactionPdata).Commit(0xc0006328c0, 0x66fecc, 0xed89d97fb)
> 
> 	D:/a/opentelemetry-collector/opentelemetry-collector/receiver/prometheusreceiver/internal/otlp_transaction.go:178 +0x1c5
> 
> github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1(0xc00001dce8, 0xc00001dcf8, 0xc00077f440)
> 
> 	C:/Users/runneradmin/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210621150501-ff58416a0b02/scrape/scrape.go:1195 +0x50
> 
> github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc00077f440, 0x3b9aca00, 0x3b9aca00, 0x0, 0x0, 0x0, 0x66fecc, 0xed89d97fb, 0x400bca0, 0x0, ...)
> 
> 	C:/Users/runneradmin/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210621150501-ff58416a0b02/scrape/scrape.go:1262 +0xb58
> 
> github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc00077f440, 0x3b9aca00, 0x3b9aca00, 0x0)
> 
> 	C:/Users/runneradmin/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210621150501-ff58416a0b02/scrape/scrape.go:1148 +0x37e
> 
> created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
> 
> 	C:/Users/runneradmin/go/pkg/mod/github.com/prometheus/prometheus@v1.8.2-0.20210621150501-ff58416a0b02/scrape/scrape.go:564 +0xa0e
> 
> ```

Thanks @bogdandrutu! Indeed, I should perhaps mark this PR as a draft because I have to translate the entire test suite, it's basically consumed most of my time for the past week. I'll actually mail small parts of it progressively.

**Comment by bogdandrutu** [comment]
@odeke-em unfortunately this needs to be moved to contrib. Sorry and thanks :)

**Pull request closed without merging**
