### PR TITLE
Add skywalking log exporter

### PR DESCRIPTION
**Pull request by liqiangz**
**Description:**  Add skywalking log exporter 

When I submitted it, I found that submitting pr now needs to be in the roadmap.
Should I move this pr to open-telemetry/opentelemetry-collector-contrib?

**Link to tracking Issue:** apache/skywalking#6209

**Testing:** 

logdata_to_logrecord_test.go

**Documentation:** 
exporter/skywalkingexporter/README.md

### CODE REVIEW

**Comment by wu-sheng** [comment]
Glad to see this.

**Comment by wu-sheng** [comment]
@bogdandrutu @rakyll @jpkrohling Could you help on this?

**Comment by kezhenxu94** [comment]
According to https://github.com/open-telemetry/opentelemetry-collector/issues/3474 and recent activities on this repo, I guess this component should land on -contrib repo

**Comment by liqiangz** [comment]
> According to #3474 and recent activities on this repo, I guess this component should land on -contrib repo

It looks like it is, I will move it.

**Comment by liqiangz** [comment]
> > According to #3474 and recent activities on this repo, I guess this component should land on -contrib repo
> 
> It looks like it is, I will move it.

This pr is moved to https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/4956.

**Pull request closed without merging**
