### PR TITLE
Fix support for new line in config URI location

### PR DESCRIPTION
**Pull request by bogdandrutu**
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/6306

### CODE REVIEW

**Review by codeboten — APPROVED** [review]
Restarted the windows tests, don't think their failure was related

**Comment by bogdandrutu** [comment]
@codeboten do you know if this should go on the release branch, then merge into main or the other way around?

**Comment by codeboten** [comment]
@bogdandrutu as per @Aneurysm9's  comment in a slack thread:

1. make change on release/v0.62.x
2. tag and release commit at head of release/v0.62.x
3. merge release/v0.62.x into main with a three-way merge to ensure that the tagged commit from release/v0.62.x is in the history of the head of main

**Pull request merged**
