### PR TITLE
[exporter/logging] Remove logging exporter

### PR DESCRIPTION
**Pull request by TylerHelmuth**
#### Description

It is September, which means we get to remove this deprecated component.

- The helm chart was updated to exclude the logging exporter already: https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md#0840-to-0850.
- The Operator references have been updated: https://github.com/open-telemetry/opentelemetry-operator/pull/3259.
- Opentelemetry.io site final references to update: https://github.com/open-telemetry/opentelemetry.io/pull/5143

#### Link to tracking issue
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/7769

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Review by mx-psi — DISMISSED** [review]
There are a bunch of references on examples in language library repositories still that mention the logging exporter. This search has a lot of false positives, but it's a good start I think: https://github.com/search?q=org%3Aopen-telemetry+%22logging%3A%22+-repo%3Aopen-telemetry%2Fopentelemetry-collector+language%3AYAML+OR+language%3AMarkdown&type=code&p=1

We also have ~18% of survey respondents from [the Collector survey raw data](https://github.com/open-telemetry/sig-end-user/blob/main/end-user-surveys/otel-collector/otel-collector-survey.csv) using the logging exporter so I think we need to do this very carefully. 

At a minimum I feel like we need a migration page, and a very clear error message that tells you to use the debug exporter and links you to the migration page. Additionally, it would be great to have something like #7631 before we do this (not sure if it should be a hard requirement tho).

I am blocking this until we at least have no references to the logging exporter within examples in the OpenTelemetry org

**Comment by TylerHelmuth** [comment]
@mx-psi it has been another 4 weeks with an even louder warning and @codeboten has updated a majority of the loggingexporter references in language repos.  I feel we should move forward with this removal.

**Review by songy23 — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]

**Review by codeboten — APPROVED** [review]
I've opened PRs to most of the remaining references to the `logging` exporter found in the query that were not in archived repositories.

I don't know that it's worth waiting for all of them to be merged before moving this forward.

**Review by djaglowski — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@mx-psi added an additional warning:

```yaml
receivers:
  otlp:
    protocols:
      grpc:
exporters:
  logging:
    level: debug
service:
  pipelines:
    traces:
      receivers:
        - otlp
      exporters:
        - logging
```

```
❯ ./bin/otelcorecol_darwin_arm64 --config ./bin/config.yaml
Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': the logging exporter has been deprecated, use the debug exporter instead
2024/10/01 08:55:31 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):

error decoding 'exporters': the logging exporter has been deprecated, use the debug exporter instead
```

**Review by mx-psi — COMMENTED** [review]
IMO this is ready to merge once we remove the exporter from the opentelemetry-collector-releases manifests

**Comment by TylerHelmuth** [comment]
Releases PR: https://github.com/open-telemetry/opentelemetry-collector-releases/pull/682

**Comment by mx-psi** [comment]
I pinned issue #11337 which we can use as the central place for any people that need help with the migration. We can keep it pinned and open for a couple weeks and close it after a while. 

I think this has enough approvals to merge so I am merging, thanks everyone for the hard work, let's hope this goes smoothly!

**Pull request merged**
