### PR TITLE
[service] fix: use ipv6-aware host and port concatenation function

### PR DESCRIPTION
**Pull request by terakoya76**
#### Description
Fixing the bug: the latest version of otel-collector failed to start with ipv6 metrics endpoint service telemetry.

This problem began to occur after https://github.com/open-telemetry/opentelemetry-collector/pull/9037 with the feature gate flag enabled was merged. This problem is probably an implementation omission because the enabled codepath, which was originally added by https://github.com/open-telemetry/opentelemetry-collector/pull/7871, is marked as WIP.

You can reproduce the issue with the config and the environment variable (`MY_POD_IP=::1`).
```yaml
service:
  telemetry:
    logs:
      encoding: json
    metrics:
      address: '[${env:MY_POD_IP}]:8888'
```

#### Link to tracking issue
Fixes https://github.com/open-telemetry/opentelemetry-collector/issues/10011

#### Testing
Added unittests to ensure the collector service to work with ipv6 metrics endpoint service telemetry.

I wondered whether to add a `network` argument, which is used as switching flag, to the `GetAvailableLocalAddress` function or create a new dedicated function for IPv6.
Since the `GetAvailableLocalAddress` function is widely used and its usage is usually assumed to be for IPv4, I chose the latter, not wanting to add more arguments each time we call.

### CODE REVIEW

**Comment by terakoya76** [comment]
Is there anything else I have to do to get a review?

Note: I did not add a change log because I assumed that changes were made only to internal packages. If this is an incorrect understanding, please point it out.

**Comment by marcus-griep-simplisafe** [comment]
Tracking this, as it's causing problems with being able to use an up-to-date OTel collector in some IPv6 applications.

**Review by TylerHelmuth — COMMENTED** [review]
@terakoya76 sorry that I missed this PR.  Everything looks good to me. Please add a `bug_fix` changelog entry.

**Comment by terakoya76** [comment]
@TylerHelmuth
Thanks. I added a change log entry.

**Review by TylerHelmuth — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Pull request merged**
