### PR TITLE
Remove typo

### PR DESCRIPTION
**Pull request by will-sargent-eero**
Fix typo

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@will-sargent-eero can you please sign the CLA, thank you.

**Review by rakyll — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@will-sargent-eero please sign the CLA, until then the merging of your PRs is blocked.

**Comment by carlosalberto** [comment]
@will-sargent-eero ping ;)

**Comment by will-sargent-eero** [comment]
@carlosalberto this is my work account, and the legal stuff is odd there -- eero is a subsiduary of Amazon but "not" Amazon according to the CLA engine?

I think it may be better to close this and redo it outside :-/

**Comment by carlosalberto** [comment]
@will-sargent-eero thanks, opened a PR with this change. Thanks! (and guess we can close this PR ;) )

**Pull request closed without merging**
