### PR TITLE
Fix trace jaeger conversion to internal traces zero time bug

### PR DESCRIPTION
**Pull request by Vemmy124**
**Description:**
Fixing a bug. When spans are converted from internal trace to jaeger trace the conversion is `zero timestamp -> time.Time{}` which is a reserved date.  When converted back, this date is interpreted as a usual one, so `ProtoBatchesToInternalTraces(InternalTracesToJaegerProto(traces)) != traces`. So I added a check on this one

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Please add a test to verify the bug fix.

**Comment by Vemmy124** [comment]
Well, I think it is better to add function to timestamp package for that and test it there

**Comment by Vemmy124** [comment]
@tigrannajaryan does it look good now?

**Review by tigrannajaryan — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
