### PR TITLE
feat: support env substitution in config file

### LINKED ISSUE #4384: Fallback values for $ENV in config.yaml
**Is your feature request related to a problem? Please describe.**

In cases where config.yml relies on environment variables (example)

```yaml
oauth2client:
    client_id: "${CLIENT_ID}"
```

it would be nice to have some way to specify fall back environment var if the env variable is not set instead of evaluating to blank string. Something in lines of 

```yaml
oauth2client:
    client_id: "${CLIENT_ID:<default-id>}"
```

### PR DESCRIPTION
**Pull request by cuichenli**
**Description:**
Add the ability to specify shell compatible variable substitution in the config file. 

**Link to tracking Issue:** Fixes #4384

### CODE REVIEW

**Review by jpkrohling — APPROVED** [review]
Looks OK to me, I'm just not a huge fan of the extra dependency.

**Review by bogdandrutu — CHANGES_REQUESTED** [review]
Please add an issue and explain why this is needed.

**Comment by jcchavezs** [comment]
Is this related to this comment? https://github.com/open-telemetry/opentelemetry-collector/pull/4098#issuecomment-947457653

**Comment by bogdandrutu** [comment]
@jcchavezs that comment seems wrong to me because we have tests where that works. Can you clarify that? This is not related to that it is to expand more the current functionality.

**Comment by pavankrish123** [comment]
I think @cuichenli updated the Link to tracking Issue: Fixes #4384

**Comment by cuichenli** [comment]
@~bogdandrutu commented in the original issue that we need more discussions, hence I am going to close this pr now.

**Pull request closed without merging**
