### PR TITLE
remove locking from jaeger receiver start and stop processes

### PR DESCRIPTION
**Pull request by bhautikpip**
**Description:** <Describe what has changed. 
Remove locking from start and stop functions - jaeger receiver

**Link to tracking Issue:** <Issue number if applicable>
https://github.com/open-telemetry/opentelemetry-collector/issues/3041

**Testing:** < Describe what testing was performed and which tests were added.>

**Documentation:** < Describe the documentation added.>

_Please delete paragraphs that you did not use before submitting._

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@bhautikpip have you confirmed that this is not needed?

**Comment by bhautikpip** [comment]
@bogdandrutu I have not tested this changes with multiple requests to see wether we would be requiring locks or not. I kinda followed the issue description.  Any recommendation on best way to test this?

**Comment by jrcamp** [comment]
I think the field `mu sync.Mutex` can be removed as well. Would run the tests with -race. The locks are taken during Startup and Shutdown which shouldn't happen concurrently. Not sure of any other good way to test.

**Comment by bhautikpip** [comment]
Ran `jaegerreceiver` package tests using `go test -race go.opentelemetry.io/collector/receiver/jaegerreceiver` command and could not find any data races warning.

**Comment by jrcamp** [comment]
@jpkrohling

**Review by jrcamp — APPROVED** [review]

**Review by jpkrohling — APPROVED** [review]

**Pull request merged**
