### PR TITLE
Honor Prometheus external labels

### LINKED ISSUE #2904: prometheus receiver : external labels are not honored
external lables specified in the global config are not flowing. Its hard to use re-labeling to add same label to every job.

### PR DESCRIPTION
**Pull request by rakyll**
Add external labels to every scraped sample in the Prometheus receiver if user has external labels configured.

Fixes #2904.
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/3016.

### CODE REVIEW

**Comment by rakyll** [comment]
cc @Aneurysm9 @odeke-em

**Comment by rakyll** [comment]
Can I get a review, @Aneurysm9 @odeke-em?

**Review by Aneurysm9 — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Review by gramidt — APPROVED** [review]
Looks good! LGTM

**Comment by alolita** [comment]
@open-telemetry/collector-approvers can you please review asap? Thanks! Ping @jpkrohling

**Review by carlosalberto — APPROVED** [review]

**Comment by rakyll** [comment]
Can someone merge this PR? It's been sitting here for a long time and is important for Prometheus compliance.

cc @bogdandrutu

**Comment by alolita** [comment]
@bogdandrutu can you please merge this PR? Its been reviewed and is awaiting to be merged. Many thanks.

**Review by bogdandrutu — APPROVED** [review]

**Comment by jpkrohling** [comment]
For the record, I also missed the notification for this one.

**Pull request merged**
