### PR TITLE
Convert pdata generated code to use time.Time instead of custom type

### PR DESCRIPTION
**Pull request by bogdandrutu**
Updates #2488

Important Changes:
* All time related accessors return time.Time instead of pdata.TimestampUnixNanos
* Methods called `Timestamp` renamed to `Time`
* Remove pdata.TimestampUnixNanos and helpers
* Fix bug around `IsZero`, this function should return true if the time is `January 1, year 1, 00:00:00 UTC` not epoch.

Current PR does conversion on the fly, but we can improve this by converting only when marshal and unmarshal.

Benchmarks for current implementation:
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/consumer/pdata
BenchmarkGetTime
BenchmarkGetTime-16    	306094170	         3.56 ns/op	       0 B/op	       0 allocs/op
BenchmarkSetTime
BenchmarkSetTime-16    	907097787	         1.21 ns/op	       0 B/op	       0 allocs/op
PASS
```

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
>All time related accessors return time.Time instead of pdata.TimestampUnixNanos

Why are we doing this? `time.Time` is a more complicated and slow data structure. What was wrong with pdata.TimestampUnixNanos?

**Comment by bogdandrutu** [comment]
> Why are we doing this? time.Time is a more complicated and slow data structure. What was wrong with pdata.TimestampUnixNanos?

There are multiple reasons to do this:
1. `time.Time` is a standard golang struct, which means users are familiar with it and it's behaviors
2. `time.Time` is a bit more complicated but we rely on the golang official library to do the translation, so our code is not more complicated.
3. `time.Time` is a bit slower indeed, but not by much, we are talking about couple of cpu cycles to covert to/from it.

**Comment by tigrannajaryan** [comment]
I am worried that the impact for metrics will be significant (with 2 timestamps per data point). Maybe benchmark to be sure the impact is small? 

>time.Time is a standard golang struct, which means users are familiar with it and it's behaviors

The counterargument is that we don't really need to do much with the time except converting it from/to other time formats. The benefit of using standard golang time seems small and we are trading it off for some (unknown until we benchmark) amount of performance.

I am not against the change but would like to understand the tradeoff better.

**Comment by bogdandrutu** [comment]
> The counterargument is that we don't really need to do much with the time except converting it from/to other time formats. The benefit of using standard golang time seems small and we are trading it off for some (unknown until we benchmark) amount of performance.

* Jaeger uses `time.Time`
* Zipkin v2 uses `time.Time`
* Prometheus uses uint64 timestamp but in millis (probably almost same cost)

**Pull request closed without merging**
