### PR TITLE
record a metric with open census to ensure backwards compat

### PR DESCRIPTION
**Pull request by codeboten**
The healthcheck extension currently relies on an OpenCensus view to determine the health of the collector. This behaviour is not great as it only looks at span exports, but it exists today. To avoid breaking it, I suggest this PR that adds the same OC view even on the otel path, and records the same metric.

Note to reviewers: This is only a hack that's needed until the new healthcheck extension that uses component status is ready to go. cc @mwear

### CODE REVIEW

**Review by mwear — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
Oh I see now that we already have a way forward for the healthcheckextension, and this is a hack until then

**Comment by TylerHelmuth** [comment]
@mwear @codeboten you got a link to the healthcheckextension issue that, when closed, means we can remove this hack?  Can we also open an issue to track the removal of this hack?

**Comment by codeboten** [comment]
@TylerHelmuth This issue captures most of the problems w/ the healthcheck extension with this issue https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26661 capturing the refactoring of it. I can create an issue to track removing this hack once https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/26661 is done

**Comment by codeboten** [comment]
@TylerHelmuth added https://github.com/open-telemetry/opentelemetry-collector/issues/9069

**Review by TylerHelmuth — APPROVED** [review]

**Comment by codeboten** [comment]
Closing this PR. After further investigation, the behaviour in the current healthcheck extension doesn't work as expected. It registers itself as an OpenCensus exporter to be called when census wants to emit a metric. For the `exporter/send_failed_requests`, this export is triggered every 10s, rather than every time a failure is recorded.

In addition, the extension does not read the value of the metric, which means the threshold it calculates is solely based on the number of times the view is exported, which has no correlation to failures to export.

Since the view is configured only to record measurements for span exports, the healthcheck extension only ever triggered for a single signal, which doesn't make it overly useful.

After discussing this with other collector approvers and maintainers, we've decided to flag the feature as not working as expected in the healthcheck extension. Since this extension is being revamped to use component status, it isn't worth fixing in the short term. I'll open a PR to update the README to warn users of this issue, this is only to prevent a breaking change multiple times in short successions for users. cc @TylerHelmuth @mx-psi

**Pull request closed without merging**
