### PR TITLE
Add filtering for logs

### PR DESCRIPTION
**Pull request by chaitanyaphalak**
**Description:** Adding a feature to filter logs based on resource attributes to the filterprocessor

**Testing:** Added Unit tests for sanity checks

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@bogdandrutu is there anything new on the decision about splitting processors by data type? If not yet then I think we should proceed and add log support to the existing filter processor for now.

**Comment by tigrannajaryan** [comment]
> @bogdandrutu is there anything new on the decision about splitting processors by data type? If not yet then I think we should proceed and add log support to the existing filter processor for now.

@chaitanyaphalak it may be worth raising this in today's Collector SIG meeting. (I am not sure I will attend today).

**Comment by chaitanyaphalak** [comment]
@tigrannajaryan I raised it in the meeting yesterday with @bogdandrutu , didnt get much clarity and there are more followups

**Comment by dmitryax** [comment]
We can start with basic functionality as provided in this PR, but we should think ahead of the future config interface changes. We will likely need the same include/exclude functionality as done for metrics, as well as regex and expressions support. When we will be adding include/exclude support, current config interface for logs will have to go through a breaking change.

I suggest let's add include/exclude support. Also let's add `match_type` option with the only one option for now - `strict`. This way we will avoid any breaking changes in the config going forward

**Comment by dmitryax** [comment]
At least for this PR lets make it aligned with the config interface for metrics: only `exclude` and `match_type: strict` support. And as follow up PR would be nice to have `include` support, or at least an issue.

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@chaitanyaphalak @dmitryax you become in-charge of fixing config for this.

**Pull request merged**
