### PR TITLE
Use common json parsing code for attributes

### PR DESCRIPTION
**Pull request by bogdandrutu**
Signed-off-by: Bogdan <bogdandrutu@gmail.com>

### CODE REVIEW

**Comment by dmitryax** [comment]
I believe the code was introduced for performance benefits. Should we run benchmarks with this e.g. exisitng `BenchmarkJSONUnmarshal`?

**Comment by bogdandrutu** [comment]
The code is the same, just extracted when we added the same code for the `metrics` performance PR https://github.com/open-telemetry/opentelemetry-collector/pull/5433 but we did not change `traces` to use that common extracted code.

**Comment by bogdandrutu** [comment]
**Before:**
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/pdata/ptrace
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkJSONUnmarshal
BenchmarkJSONUnmarshal-16    	  354525	      3803 ns/op	    4669 B/op	     231 allocs/op
PASS
```

**After:**
```
goos: darwin
goarch: amd64
pkg: go.opentelemetry.io/collector/pdata/ptrace
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
BenchmarkJSONUnmarshal
BenchmarkJSONUnmarshal-16    	  319340	      3835 ns/op	    4669 B/op	     231 allocs/op
PASS
```

Time diff is within the error, but bytes and allocs are identical

**Review by dmitryax — APPROVED** [review]
LGTM

**Pull request merged**
