### PR TITLE
Standarize Settings instead of Params and Parameters

### LINKED ISSUE #2650: Standardize on params vs settings vs options
In few places for constructors we use "Params" (in the components), some "Parameters" (in the Service) or "Settings" in the components helpers like exporterhelper.

We need to decide on a name a pattern: expose a struct with these properties or expose "Options" and use variadic args.

Consolidate all interfaces to follow the same pattern.

### PR DESCRIPTION
**Pull request by pmatyjasek-sumo**
A proposal solution of standarize constructors parameters

**Description:** 
Fixes #2650
Changes:
 Replace: ReceiverCreateParams, ProcessorCreateParams, ExtensionCreateParams and ExporterCreateParams with ComponentSettings struct
 Replace all dependencies in Extensions, Exporters, Processors and Receivers
 Replace Parameters and settings structs with new struct Settings
 Replace dependencies in service and main
 Update tests

Signed-off-by: Patryk Matyjasek <pmatyjasek@sumologic.com>

**Link to tracking Issue:** <Issue number if applicable>
#2650 

**Testing:** < Describe what testing was performed and which tests were added.>
UT

**Documentation:** < Describe the documentation added.>
In code comments

### CODE REVIEW

**Comment by pmatyjasek-sumo** [comment]
@bogdandrutu @tigrannajaryan please take a look for this proposal

**Review by bogdandrutu — COMMENTED** [review]
I like the direction, we should probably start by doing smaller PRs, like changing the service package initially.

**Comment by pmatyjasek-sumo** [comment]
Thanks @bogdandrutu for the response. I'll split it into smaller PRs.

**Comment by bogdandrutu** [comment]
@pmatyjasek-sumo is this PR still useful?

**Comment by pmatyjasek-sumo** [comment]
No. I'm closing it

**Pull request closed without merging**
