### PR TITLE
[pdata] Rename pmetric.MetricDataPointFlags to pmetric.DataPointFlags

### PR DESCRIPTION
**Pull request by dmitryax**
Following pdata naming rules outlined in https://github.com/open-telemetry/opentelemetry-collector/pull/6255, we want to update the struct to have the same name as defined in protobuf package.

Updates https://github.com/open-telemetry/opentelemetry-collector/issues/6257

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
where is the DataPointFlags defined?

**Comment by dmitryax** [comment]
@bogdandrutu do you mean pdata definition? it's here https://github.com/open-telemetry/opentelemetry-collector/pull/6259/files#diff-39b6dfa0a0fdf8e13fb63075018e16a009a905cfd91c451af47768bac6268e96R23

**Comment by bogdandrutu** [comment]
>As a new rule we want to rename all the structs for proto messages defined at the package level to not have the owner prefix in its name.

Read the description.

**Comment by dmitryax** [comment]
Right, the description is a bit incorrect. This is proto enum not a message https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/metrics/v1/metrics.proto#L321. But I believe we should apply the same rule for enums. Do you think otherwise?

**Comment by dmitryax** [comment]
Updated the description

**Pull request merged**
