### PR TITLE
Set service.graph feature gate to stable

### PR DESCRIPTION
**Pull request by djaglowski**
Follows #7119

### CODE REVIEW

**Comment by bogdandrutu** [comment]
I would merge this next version after 72 release, and set the removal after 74.

**Comment by djaglowski** [comment]
I've moved this back to draft until after the next release, and updated the removal version to 74

**Review by codeboten — COMMENTED** [review]
Is this ready to review/merge now that 0.72.0 is out?

**Comment by djaglowski** [comment]
> Is this ready to review/merge now that 0.72.0 is out?

Yes, should be ready now. Thanks for the ping.

**Review by codeboten — APPROVED** [review]

**Pull request merged**
