### PR TITLE
Prepare v0.64.0

### PR DESCRIPTION
**Pull request by jpkrohling**
Closes https://github.com/open-telemetry/opentelemetry-collector/issues/6496

Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

### CODE REVIEW

**Comment by jpkrohling** [comment]
Converted to draft as I want to verify contrib builds with the latest core.

**Review by codeboten — COMMENTED** [review]
It doesn't look like any go.mod files were updated as part of the PR

**Comment by jpkrohling** [comment]
> It doesn't look like any go.mod files were updated as part of the PR

Looking at the target and later at the logs, it looks like it failed in the multimod step. I'll try to run it manually and see if I can update this PR.

**Comment by jpkrohling** [comment]
This looks better now, cloning it on a fresh local repository made it work.

**Review by bogdandrutu — APPROVED** [review]

**Review by codeboten — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
