### PR TITLE
[component] Remove deprecated DataType

### PR DESCRIPTION
**Pull request by TylerHelmuth**
#### Description

Continues the switch to use `pipeline.ID` and `pipeline.Signal`.
- Removes deprecated code
- Continues rename process for function/type changes.

#### Link to tracking issue
Related to https://github.com/open-telemetry/opentelemetry-collector/issues/9429

### CODE REVIEW

**Review by djaglowski — APPROVED** [review]

**Review by bogdandrutu — COMMENTED** [review]
Can we please make this 6 PRs one per changelog entry? That would be really appreciated for reviewers.

**Comment by TylerHelmuth** [comment]
@bogdandrutu please take a look at 

- https://github.com/open-telemetry/opentelemetry-collector/pull/11303
- https://github.com/open-telemetry/opentelemetry-collector/pull/11304
- https://github.com/open-telemetry/opentelemetry-collector/pull/11305

I will continue once those are merged.

**Comment by bogdandrutu** [comment]
Anything left here?

**Comment by TylerHelmuth** [comment]
@bogdandrutu 2 more here:

- https://github.com/open-telemetry/opentelemetry-collector/pull/11312
- https://github.com/open-telemetry/opentelemetry-collector/pull/11313

Once these are merged I'll update this PR to be the removal of `component.DataType`.

**Review by mx-psi — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@bogdandrutu this PR is now scoped to only the `component` deprecations.

**Comment by bogdandrutu** [comment]
@TylerHelmuth thank you, hope you see the power of small focus PRs :)

**Pull request merged**
