### PR TITLE
[configtelemetry] Add a read header timeout of 10s on the configtelemetry Prometheus HTTP server

### LINKED ISSUE #5699: Add `ReadHeaderTimeout` values
The following lint errors started showing up after the latest upgrade to golangci-lint:

```
golangci-lint run
config/confighttp/confighttp.go:321:10: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
        return &http.Server{
                Handler: handler,
        }, nil
config/confighttp/compression_test.go:106:12: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
                        srv := &http.Server{
                                Handler: handler,
                        }
config/confighttp/compression_test.go:204:12: G112: Potential Slowloris Attack because ReadHeaderTimeout is not configured in the http.Server (gosec)
                        srv := &http.Server{
                                Handler: httpContentDecompressor(handler),
                        }
make: *** [lint] Error 1
```

### PR DESCRIPTION
**Pull request by atoulme**
#### Description
Add 10s read header timeout on the configtelemetry Prometheus HTTP server.

#### Link to tracking issue
Fixes #5699

### CODE REVIEW

**Comment by atoulme** [comment]
@codeboten given that you created the issue, please take a look?

**Review by codeboten — COMMENTED** [review]
This is probably ok, but it's not solving the original issue correct? the places in the code that were triggering the lint failure are still unchanged?

**Comment by atoulme** [comment]
no this solves one of the lint failures, and the others are plugged via confighttp changes.

**Comment by atoulme** [comment]
See this commit and change for the other place where this occurs: https://github.com/open-telemetry/opentelemetry-collector/pull/10275/files#diff-1fadfcd3b4194004717150126d27e8a32fdaa8292ca99e81a937d26abe0998faR351

**Comment by codeboten** [comment]
Thanks @atoulme, can G112 be removed then? https://github.com/open-telemetry/opentelemetry-collector/pull/5700/files

**Comment by atoulme** [comment]
@codeboten it appears so! I have reverted the commit and added it to the PR.

**Review by codeboten — APPROVED** [review]
Thanks!!

**Review by mx-psi — APPROVED** [review]

**Pull request merged**
