### PR TITLE
Add `collector-builder` to `internal/tools`, add collector manifest, add Make rule

### PR DESCRIPTION
**Pull request by erichsueh3**
**Description:** 
This PR adds the `collector-builder` to the `internal/tools` package, adds a collector manifest that the `colletor-builder` uses to build a collector, and adds a Make rule for that. This PR is intended to be the first of 2 PRs, which both together are equivalent to PR #3992. This previous PR is split into two to first ensure that the `collector-builder` works as intended before we delete `cmd/otelcol`. 

**Link to tracking Issue:** #3928

### CODE REVIEW

**Comment by bogdandrutu** [comment]
@erichsueh3 any update on this?

**Comment by erichsueh3** [comment]
> @erichsueh3 any update on this?

Currently working on this, @jpkrohling what I am currently doing is removing my changes in `internal/tools` since the builder lives in this repository now. We don't need to check the version anymore since it lives in this repository now correct? Also, I get an error when running the builder that says `ERROR	internal/root.go:92	failed to run	{"error": "failed to update go.mod: exit status 1.` It looks like it's trying to read a `go.mod` file from a directory that is the parent of the collector repo; perhaps I didn't install the builder correctly? I currently am using `go get` and `go install` to get the builder. I can send the full error logs if needed.

**Comment by jpkrohling** [comment]
> We don't need to check the version anymore since it lives in this repository now correct? 

Correct

> I currently am using go get and go install to get the builder.

You can just run it from this repository with `pushd cmd/builder/ && go run ./ && popd`

**Comment by erichsueh3** [comment]
I've tried using `pushd cmd/builder/ && go run ./ --config ../../internal/buildscripts/builder-config.yaml --output-path ../../bin && popd` and still get the same error; here is the error I'm getting

```
Error: failed to update go.mod: exit status 1. Output: "go.opentelemetry.io/collector/cmd/builder imports
    go.opentelemetry.io/collector/component: go.opentelemetry.io/collector@v0.37.0 (replaced by ../../): reading ../../go.mod: open /Users/hsuehe/Desktop/open-o11y/go.mod: no such file or directory
go.opentelemetry.io/collector/cmd/builder imports
    go.opentelemetry.io/collector/consumer/consumererror: go.opentelemetry.io/collector@v0.37.0 (replaced by ../../): reading ../../go.mod: open /Users/hsuehe/Desktop/open-o11y/go.mod: no such file or directory
go.opentelemetry.io/collector/cmd/builder imports
    go.opentelemetry.io/collector/service: go.opentelemetry.io/collector@v0.37.0 (replaced by ../../): reading ../../go.mod: open /Users/hsuehe/Desktop/open-o11y/go.mod: no such file or directory
go.opentelemetry.io/collector/cmd/builder imports
    go.opentelemetry.io/collector/service/defaultcomponents: go.opentelemetry.io/collector@v0.37.0 (replaced by ../../): reading ../../go.mod: open /Users/hsuehe/Desktop/open-o11y/go.mod: no such file or directory
go.opentelemetry.io/collector/cmd/builder imports
    golang.org/x/sys/windows/svc: go.opentelemetry.io/collector@v0.37.0 (replaced by ../../): reading ../../go.mod: open /Users/hsuehe/Desktop/open-o11y/go.mod: no such file or directory"
```

I'm not sure why it's trying to read from `../../go.mod`.

**Comment by jpkrohling** [comment]
The problem is that your manifest YAML file set the replaces to two directories up:

```yaml
dist:
  module: github.com/open-telemetry/opentelemetry-collector-releases/core
  name: cmd-otelcol
  description: OpenTelemetry Collector Replacing cmd/otelcol
  version: 0.38.0-dev
  otelcol_version: 0.37.0

replaces:
  - go.opentelemetry.io/collector => ../../
  - go.opentelemetry.io/collector/model => ../../model
```

Given that you are generating the sources at `./bin/`, the replaces should be relative to that. Here's a working configuration, which uses 0.38.0 for the collector (which shouldn't matter, as we are replacing the collector module anyway)

```yaml
dist:
  module: github.com/open-telemetry/opentelemetry-collector-releases/core
  name: cmd-otelcol
  description: OpenTelemetry Collector Replacing cmd/otelcol
  version: 0.38.0-dev
  otelcol_version: 0.38.0

replaces:
  - go.opentelemetry.io/collector => ../
  - go.opentelemetry.io/collector/model => ../model
```

Results in:

```
$ go run ./ --config ../../internal/buildscripts/builder-config.yaml --output-path ../../bin
2021-11-10T14:23:04.677+0100    INFO    internal/root.go:100    OpenTelemetry Collector distribution builder    {"version": "dev", "date": "unknown"}
2021-11-10T14:23:04.677+0100    INFO    internal/root.go:120    Using config file       {"path": "../../internal/buildscripts/builder-config.yaml"}
2021-11-10T14:23:04.678+0100    INFO    builder/config.go:102   Using go        {"go-executable": "/usr/bin/go"}
2021-11-10T14:23:04.678+0100    INFO    builder/main.go:97      Sources created {"path": "../../bin"}
2021-11-10T14:23:04.761+0100    INFO    builder/main.go:129     Getting go modules
2021-11-10T14:23:04.815+0100    INFO    builder/main.go:108     Compiling
2021-11-10T14:23:05.575+0100    INFO    builder/main.go:115     Compiled        {"binary": "../../bin/cmd-otelcol"}
```

**Comment by erichsueh3** [comment]
I see, I've made the changes and looks like it works now!

**Review by jpkrohling — APPROVED** [review]
LGTM. Perhaps this PR could have the change to the Makefile's `run` target already, but it can be done in the follow-up PR.

```Makefile
.PHONY: run
run: build-binary-cmd-otelcol
	./bin/cmd-otelcol --config ${RUN_CONFIG} ${RUN_ARGS}
```

**Pull request merged**
