### PR TITLE
[docs] Remove processing.md

### LINKED ISSUE #8893: [docs] Move processing.md to a more appropriate place
The [docs/processing.md](https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/processing.md) document describes OTTL and the transform processor design and desiderata. 

I want to propose moving this document to contrib to `processor/transformprocessor/rfc.md` where I think it fits best, since the `docs/` folder on opentelemetry-collector has become an all-catch folder. 

Alternatively, we could move it to a `docs/rfc` or `docs/proposal` folder here to make it clear it is a historical document for designing the transform processor.

Codeowners of the transform processor (@TylerHelmuth, @kentquirk, @bogdandrutu, @evan-bradley), what do you think?

### PR DESCRIPTION
**Pull request by mx-psi**
Yet another doc removal. Fixes #8893

### CODE REVIEW

**Comment by mx-psi** [comment]
@evan-bradley @TylerHelmuth @bogdandrutu @kentquirk please review!

**Review by evan-bradley — APPROVED** [review]
Thanks!

**Review by TylerHelmuth — APPROVED** [review]

**Comment by TylerHelmuth** [comment]
@mx-psi we'll need a followup to update the OTTL docs, they reference this doc.

**Comment by bogdandrutu** [comment]
I think we are going to far with "just remove" everything because is outdated. I don't see a good replacement for this, so I think we should not remove. And in all projects/companies you will have outdated docs that you still keep around to understand the reason behind things.

**Comment by mx-psi** [comment]
@bogdandrutu The alternatives suggested in #8893 are to either move this to `docs/rfc` or `processor/transformprocessor/rfc.md`. I filed this PR because of https://github.com/open-telemetry/opentelemetry-collector/issues/8893#issuecomment-1811293119.

> in all projects/companies you will have outdated docs that you still keep around to understand the reason behind things.

I don't think the `docs/` folder is the right place for outdated docs/design documents/RFCs, we are mixing documentation with design documents and (IMHO) it is confusing. Happy to change this to a different place if the code owners of the transform processor agree on it.

**Comment by mx-psi** [comment]
@bogdandrutu @TylerHelmuth @evan-bradley I am going to close this since there is no consensus. I still think we agree that this is not the right place for this document, and I am happy to review any alternative PRs

**Pull request closed without merging**
